"""Synthetic Russian-language rules and shared lexical policy fixtures.

Identifiers and public keys are review candidates, never confirmed secrets.
Native structural inspectors may apply a different reference policy to owned
password fields; the patterns below describe lexical assignment rules only.
"""

STRICT_SECRET_LABEL_PATTERN = "(?:(?!(?:id|ид|идентификатор|имя|название|длина|политика|срок|истечение|требуется|проверка|public|публичн[а-яё]{0,8}|открыт[а-яё]{0,8})[_-])[\\w]{1,40}[_-]|(?:новый|старый|текущий|временный|основной|резервный|доменный|локальный|служебный)[ \\t_\\-\\u00a0]{0,4})?(?:(?:пароль(?:[ \\t_\\-\\u00a0]{0,4}(?:(?:для|от|к)[ \\t_\\-\\u00a0]{0,4})?(?:администратора(?:[ \\t_\\-]{0,4}(?:бд|домена|сервера))?|админа|пользователя|уч[её]тной[ \\t_\\-\\u00a0]{0,4}записи|уч[её]тки|аккаунта|домена|сервер[ау]|сервис[ау]|службы|приложения|клиента|сайта|архив[ау]|хранилищ[ау]|конфигуратора|входа|подключения|доступа|базы[ \\t_\\-\\u00a0]{0,4}данных|бд|database|db|vpn|api|апи|wi[ \\t_\\-\\u00a0]{0,4}fi|wifi|1с|1c))?|парольн(?:ая|ую)[ \\t_\\-\\u00a0]{0,4}фраза|пароль[ \\t_\\-\\u00a0]{0,4}фраза)|(?:(?:api|апи)[ \\t_\\-\\u00a0]{0,4}токен|токен(?:[ \\t_\\-\\u00a0]{0,4}(?:доступа|обновления|авторизации|аутентификации|бота|клиента|приложения|сервиса|api|апи))?)|(?:секрет(?:[ \\t_\\-\\u00a0]{0,4}(?:клиента|приложения|сервиса|бота|api|апи))?|клиентск(?:ий|ого)[ \\t_\\-\\u00a0]{0,4}секрет)|(?:(?:api|апи)[ \\t_\\-\\u00a0]{0,4}ключ|ключ[ \\t_\\-\\u00a0]{0,4}(?:api|апи|доступа|авторизации)|(?:секретн(?:ый|ого)|закрыт(?:ый|ого)|приватн(?:ый|ого))[ \\t_\\-\\u00a0]{0,4}ключ)|(?:(?:пин|pin)(?:[ \\t_\\-\\u00a0]{0,4}код)?|(?:резервн(?:ый|ого)|одноразов(?:ый|ого))[ \\t_\\-\\u00a0]{0,4}код|код[ \\t_\\-\\u00a0]{0,4}(?:доступа|восстановления|подтверждения)|кодовое[ \\t_\\-\\u00a0]{0,4}слово))"

IDENTIFIER_LABEL_PATTERN = "(?:логин(?:[ \\t_\\-\\u00a0]{0,4}(?:пользователя|администратора|админа|бд|сервиса))?|имя[ \\t_\\-\\u00a0]{0,4}пользователя|имя[ \\t_\\-\\u00a0]{0,4}уч[её]тной[ \\t_\\-\\u00a0]{0,4}записи|ключ|(?:публичный|открытый)[ \\t_\\-]{1,4}(?:токен|ключ)|(?:имя|название|идентификатор)[ \\t_\\-]{1,4}(?:пароля|пароль|токена|токен|ключа|ключ))"

PLACEHOLDER_PATTERN = "(?:null|none|redacted|masked|undefined|unknown|changeme|change_me|password_here|your_password|not[ \\t_\\-\\u00a0]{0,4}set|\\*{3,}|\\[redacted\\]|<redacted>|не[ \\t_\\-\\u00a0]{0,4}(?:задан[ао]?|указан[ао]?|установлен[ао]?|известен|известно|требуется)|отсутствует|пусто|нет|неизвестно|скрыт[ао]?|удал[её]н[ао]?|заменить|по[ \\t_\\-\\u00a0]{0,4}запросу|(?:укажите|введите|вставьте|задайте)[ \\t_\\-\\u00a0]{0,4}(?:ваш[ \\t_\\-\\u00a0]{0,4})?(?:пароль|секрет|токен|ключ)(?:[ \\t]{1,4}(?:здесь|тут|ниже|в[ \\t_\\-\\u00a0]{0,4}настройках))?|\\[(?:скрыт[ао]?|удал[её]н[ао]?|не[ \\t_\\-\\u00a0]{0,4}задан[ао]?)\\]|<(?:пароль|скрыт[ао]?|секрет|токен)>|\\$[\\w][\\w.:-]{0,127}|\\$\\{[^{}\\x00\\r\\n]{1,128}\\}|\\$\\([^()\\x00\\r\\n]{1,128}\\)|\\{\\{[^{}\\x00\\r\\n]{1,128}\\}\\}|%[\\w]{1,128}%|(?:переменные|параметры|окружение)(?:\\.[\\w]{1,64}){1,6}|не[ \\t\\u00a0]{1,8}(?:менее|более)[ \\t\\u00a0]{1,8}[0-9]{1,4}[ \\t\\u00a0]{1,8}(?:символ(?:а|ов)?|знак(?:а|ов)?)|(?:хранится|находится)[ \\t\\u00a0]{1,8}(?:в|на)[ \\t\\u00a0]{1,8}(?:хранилище|сейфе|vault|сервере|переменной)|(?:укажите|введите)[ \\t\\u00a0]{1,8}(?:ваш[ \\t\\u00a0]{1,8})?пароль[ \\t\\u00a0]{1,8}в[ \\t\\u00a0]{1,8}(?:конфигурации|хранилище)|(?:спросите|запросите|уточните)[ \\t\\u00a0]{1,8}у[ \\t\\u00a0]{1,8}(?:администратора|владельца))"

UNQUOTED_REFERENCE_PATTERN = "(?:(?:[\\w]{1,64}\\.){0,4}[\\w]{1,64}\\([^\\x00\\r\\n()]{0,128}\\)|Read-Host(?:[ \\t][^\\r\\n]{0,128})?|Get-Credential(?:[ \\t][^\\r\\n]{0,128})?)"

CONTENT_CASES = [
    ("документы/настройки.txt", "PIN=1234", "russian-secret-assignment"),
    ("документы/настройки.txt", 'DB_pin="1234"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'DB_API ключ="СекретКлюча!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'DB_PIN код="1234"', "russian-secret-assignment"),
    (
        "документы/настройки.txt",
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_API    ключ="ПредельныйКлюч!"',
        "russian-secret-assignment",
    ),
    ("документы/настройки.txt", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_pin=1234", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Δεδομένα_пароль="РусскийСекрет!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Публичный токен = ИдентификаторСервиса", "russian-access-identifier-assignment"),
    ("документы/настройки.txt", "Имя пароль = НазваниеПоля", "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'Пароль="ХранитсяВХранилище!2027"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Непубличный_токен="НастоящийСекрет!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль: «Русская фраза!».", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль к серверу="ДоступКСерверу!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'пароль администратора БД="АдминБазы!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "строка\nподключения", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "закрытый\nключ", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", 'пароль: "СложныйПароль!2027"', "russian-secret-assignment"),
    ("документы/настройки.txt", "ПАРОЛЬ=ЁжикИОблако!", "russian-secret-assignment"),
    ("документы/настройки.txt", 'ПарольАдминистратора="СлужебныйПароль!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "пароль_БД=БазаДанных!27", "russian-secret-assignment"),
    ("документы/настройки.txt", "DB_пароль=БазаДанных!27", "russian-secret-assignment"),
    ("документы/настройки.txt", "БД_Пароль=БазаДанных!27", "russian-secret-assignment"),
    ("документы/настройки.txt", 'ДоменныйПароль: "Доменный Секрет!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'пароль учётной записи: "УчётнаяФраза!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'пароль учетной записи="УчетнаяФраза!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'пароль от базы данных = "Пароль Базы!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'токен доступа="токен_Жёлтый_123"', "russian-secret-assignment"),
    ("документы/настройки.txt", "ТОКЕН_ОБНОВЛЕНИЯ: RefreshFixture123!", "russian-secret-assignment"),
    ("документы/настройки.txt", 'секрет клиента = "КлиентскийСекрет!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'клиентский секрет="СекретКлиента!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'API-ключ = "АПИ_Секрет_123"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'ключ API: "КлючСервиса!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "ключ доступа: КлючДоступа!", "russian-secret-assignment"),
    ("документы/настройки.txt", 'приватный ключ = "ПриватныйМатериал!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'парольная фраза: "Три разных русских слова!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "ПарольнаяФраза=Очень Длинная Фраза!", "russian-secret-assignment"),
    ("документы/настройки.txt", "ПИН-код=1234", "russian-secret-assignment"),
    ("документы/настройки.txt", "код восстановления=1234-5678-9012", "russian-secret-assignment"),
    ("документы/настройки.txt", "резервный код: 12345678", "russian-secret-assignment"),
    ("документы/настройки.txt", 'кодовое слово = "Секретный Ёж"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль — «Сложный пароль!»", "russian-secret-assignment"),
    ("документы/настройки.txt", "пароль – “Кодовая фраза!”", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль := "РусскийPascal!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль => "РусскийMapping!"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="НеЗадан!2027"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Скрыто!2027"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Отсутствует!НоЭтоПароль"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="укажите пароль!2027"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="true"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=я", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль=" $ОченьСложно! "', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Обычное русское слово"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=Ёжик#27!", "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=Очень(Сложно)!", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Функция()"', "russian-secret-assignment"),
    (
        "документы/настройки.txt",
        '{"ПарольАдминистратора":"Цитата\\"Внутри!","Описание":"проверка"}',
        "russian-secret-assignment",
    ),
    ("документы/настройки.txt", "пароль не задан", "russian-credential-language-signal"),
    ("документы/настройки.txt", "Требуется аутентификация", "russian-credential-language-signal"),
    ("документы/настройки.txt", "УЧЁТНЫЕ ДАННЫЕ", "russian-credential-language-signal"),
    ("документы/настройки.txt", "учетные записи", "russian-credential-language-signal"),
    ("документы/настройки.txt", "ПарольАдминистратора", "russian-credential-language-signal"),
    ("документы/настройки.txt", "пароль_БД", "russian-credential-language-signal"),
    ("документы/настройки.txt", "секрет клиента", "russian-credential-language-signal"),
    ("документы/настройки.txt", "токен обновления", "russian-credential-language-signal"),
    ("документы/настройки.txt", "Доступ к серверу", "russian-credential-language-signal"),
    ("документы/настройки.txt", "доступ\nк ресурсу", "russian-credential-language-signal"),
    ("документы/настройки.txt", "ПИН_КОД", "russian-credential-language-signal"),
    ("документы/настройки.txt", "API-ключ", "russian-credential-language-signal"),
    ("документы/настройки.txt", "код восстановления", "russian-credential-language-signal"),
    ("документы/настройки.txt", "кодовое слово", "russian-credential-language-signal"),
    ("документы/настройки.txt", "ключ: идентификатор", "russian-credential-language-signal"),
    ("документы/настройки.txt", "закрытый ключ", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "ЗакрытыйКлюч", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "открытый_ключ", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "публичный ключ", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "сертификаты", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "подпись", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "электронная подпись", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "УКЭП", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "ЭЦП", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "ключ_шифрования", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "криптоконтейнер", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "расшифровка", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "Строка подключения", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "СтрокаПодключения", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "строка_подключения", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "БД: Склад", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "база данных: Склад", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "базы данных: Склад", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "источник данных", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "ИсточникДанных", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "параметры подключения", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "информационная база", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "подключение к БД", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "сервер БД", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "логин=Администратор", "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'ЛОГИН: "служебный пользователь"', "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'имя пользователя="Иван"', "russian-access-identifier-assignment"),
    ("документы/настройки.txt", "ИмяПользователя=Пётр", "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'имя учётной записи="ДОМЕН\\\\Иван"', "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'ключ="ОткрытыйИдентификатор"', "russian-access-identifier-assignment"),
    ("пользователи.json", '{"Описание":"пароль=Ёжик_Учётки!","Имя":"Иван"}', "ad-directory-credential-note"),
    ("users.ldf", 'description: токен доступа="ТокенУчётки!"', "ad-directory-credential-note"),
    ("users.ldf", "info: API-ключ=КлючУчётки!", "ad-directory-credential-note"),
    ("учетные-записи.txt", "Примечание: резервный код=12345678", "ad-directory-credential-note"),
    ("пользователи.json", '{"Комментарий":"секрет клиента=\\"ЖёлтыйСекрет!\\""}', "ad-directory-credential-note"),
    ("компьютеры.txt", "Описание: ПарольАдминистратора=ЁжикКомпьютера!", "ad-directory-credential-note"),
    ("users.ldf", 'description: пароль="Скрыто!2027"', "ad-directory-credential-note"),
]

NEGATIVE_CASES = [
    ("документы/настройки.txt", "Пароль: не менее 12 символов", "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль: укажите пароль в конфигурации", "russian-secret-assignment"),
    ("документы/настройки.txt", "Токен доступа: хранится в хранилище", "russian-secret-assignment"),
    ("документы/настройки.txt", "Публичный токен = ИдентификаторСервиса", "russian-secret-assignment"),
    ("документы/настройки.txt", "ПУБЛИЧНЫЙ   токен = ИдентификаторСервиса", "russian-secret-assignment"),
    ("документы/настройки.txt", "Имя пароль = НазваниеПоля", "russian-secret-assignment"),
    ("users.ldf", "description: пароль=не менее 12 символов", "ad-directory-credential-note"),
    ("users.ldf", "description: Публичный токен=ИдентификаторСервиса", "ad-directory-credential-note"),
    ("документы/настройки.txt", 'Пароль="не задан"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=не задан", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Не Указан"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=Не Указан", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="не установлен"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=не установлен", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="отсутствует"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=отсутствует", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="скрыто"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=скрыто", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="удалён"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=удалён", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="удален"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=удален", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="укажите пароль"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=укажите пароль", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="введите ваш пароль"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=введите ваш пароль", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="укажите пароль в настройках"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=укажите пароль в настройках", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="нет"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=нет", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="пусто"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=пусто", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="[СКРЫТО]"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=[СКРЫТО]", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="<пароль>"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=<пароль>", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="${ПАРОЛЬ}"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=${ПАРОЛЬ}", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="%ПАРОЛЬ%"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=%ПАРОЛЬ%", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="{{ пароль }}"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль={{ пароль }}", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="$Пароль"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=$Пароль", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="$(ПолучитьПароль)"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=$(ПолучитьПароль)", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Переменные.Пароль"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=Переменные.Пароль", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="Параметры.Пароль"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=Параметры.Пароль", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="REDACTED"', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=REDACTED", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="  не задан  "', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=  не задан  ", "russian-secret-assignment"),
    (
        "документы/настройки.txt",
        'Пароль="                                        скрыто                                        "',
        "russian-secret-assignment",
    ),
    (
        "документы/настройки.txt",
        "Пароль=                                        скрыто                                        ",
        "russian-secret-assignment",
    ),
    ("документы/настройки.txt", "логин=Администратор", "russian-secret-assignment"),
    ("документы/настройки.txt", 'имя пользователя="Иван"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'ключ="Идентификатор"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'ОткрытыйКлюч="ПубличныеДанные!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "публичный ключ: ABCDEFGH", "russian-secret-assignment"),
    ("документы/настройки.txt", 'ID_токен="ИдентификаторТокена!"', "russian-secret-assignment"),
    ("документы/настройки.txt", "длина_пароль=12", "russian-secret-assignment"),
    ("документы/настройки.txt", 'Политика_пароль="СложнаяПолитика"', "russian-secret-assignment"),
    ("документы/настройки.txt", 'парольная политика="ДвенадцатьСимволов"', "russian-secret-assignment"),
    ("документы/настройки.txt", "минимальная длина пароля: 12", "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль должен содержать 12 символов", "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=$Переменные.Пароль", "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=ПолучитьПароль()", "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль=Read-Host -AsSecureString", "russian-secret-assignment"),
    ("документы/настройки.txt", '{"Пароль": false}', "russian-secret-assignment"),
    ("документы/настройки.txt", '{"Пароль": true}', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль=""', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="   "', "russian-secret-assignment"),
    ("документы/настройки.txt", 'Пароль="НетЗакрывающейКавычки', "russian-secret-assignment"),
    ("документы/настройки.txt", "Пароль==ОперацияСравнения!", "russian-secret-assignment"),
    ("документы/настройки.txt", "непароль=ДругиеДанные!", "russian-secret-assignment"),
    ("документы/настройки.txt", "секретарь директора", "russian-credential-language-signal"),
    ("документы/настройки.txt", "Секретариат организации", "russian-credential-language-signal"),
    ("документы/настройки.txt", "бухгалтерский баланс", "russian-credential-language-signal"),
    ("документы/настройки.txt", "методология разработки", "russian-credential-language-signal"),
    ("документы/настройки.txt", "подписка на новости", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "ключевая ставка", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "подписной каталог", "russian-cryptography-language-signal"),
    ("документы/настройки.txt", "бдительность", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "бадминтон", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", "строка текста", "russian-data-connection-language-signal"),
    ("документы/настройки.txt", 'логин=""', "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'логин="   "', "russian-access-identifier-assignment"),
    ("документы/настройки.txt", "логин=${ПОЛЬЗОВАТЕЛЬ}", "russian-access-identifier-assignment"),
    ("документы/настройки.txt", 'имя файла="readme.txt"', "russian-access-identifier-assignment"),
    ("users.ldf", "description: пароль=отсутствует", "ad-directory-credential-note"),
    ("users.ldf", 'description: пароль=" не задан "', "ad-directory-credential-note"),
    ("users.ldf", 'description: пароль="укажите пароль"', "ad-directory-credential-note"),
    ("users.ldf", "description: логин=Администратор", "ad-directory-credential-note"),
    ("users.ldf", 'description: ОткрытыйКлюч="ОткрытыеДанные!"', "ad-directory-credential-note"),
    ("users.ldf", "description: публичная заметка\nпароль=ВнеЗаметки!", "ad-directory-credential-note"),
    ("пользователи.json", '{"Описание":"публичная заметка","Пароль":"ВнеЗаметки!"}', "ad-directory-credential-note"),
    ("пользователи.json", '{"Описание":"пароль=", "ДругаяСтрока":"ВнеЗаметки!"}', "ad-directory-credential-note"),
    ("пользователи.json", '{"Описание":"пароль=\\"${ПАРОЛЬ}\\""}', "ad-directory-credential-note"),
    ("unrelated.json", '{"Описание":"пароль=НеКаталог!"}', "ad-directory-credential-note"),
]
