"""Synthetic positive/negative cases and primary sources for the 2.4 content expansion.

Tokens below are inert format fixtures, never credentials obtained from a provider.
Prefix/format matching does not establish validity or verify embedded checksums.
"""

CONTENT_CASES = (
    ("keys/identity.key", "AGE-SECRET-KEY-1" + "Q" * 58, "age-secret-identity"),
    ("keys/identity.agekey", "AGE-SECRET-KEY-PQ-1" + "Q" * 160, "age-secret-identity"),
    ("notes.txt", "glsa_" + "aB9c" * 8 + "_0123abcd", "grafana-service-account-token"),
    ("telemetry/.env", "glc_" + "eyJr" * 30 + "==", "grafana-cloud-access-token"),
    ("cloud.json", '"key":"dop_v1_' + "a1b2c3d4" * 8 + '"', "digitalocean-access-token"),
    ("cloud.json", "doo_v1_" + "a1b2c3d4" * 8, "digitalocean-access-token"),
    ("cloud.json", "dor_v1_" + "a1b2c3d4" * 8, "digitalocean-access-token"),
    ("vpn.yml", "tskey-auth-AbC9dE12345-" + "xY2z" * 8, "tailscale-access-token"),
    ("vpn.yml", "tskey-api-AbC9dE12345-" + "xY2z" * 8, "tailscale-access-token"),
    ("vpn.yml", "tskey-app-AbC9dE12345-" + "xY2z" * 8, "tailscale-access-token"),
    ("nats/account.creds", "-----BEGIN USER NKEY SEED-----\nSU" + "A2" * 28, "nats-nkey-seed"),
    ("nats/operator.nk", "SO" + "A2" * 28, "nats-nkey-seed"),
    ("nats/server.seed", "SN" + "A2" * 28, "nats-nkey-seed"),
    ("bootstrap.yml", "token: a1b2c3.d4e5f6g7h8i9j0k1", "kubernetes-bootstrap-token"),
    ("join.sh", "kubeadm join cluster:6443 --token=a1b2c3.d4e5f6g7h8i9j0k1", "kubernetes-bootstrap-token"),
    ("audit.log", "Authorization: Bearer a1b2c3.d4e5f6g7h8i9j0k1", "kubernetes-bootstrap-token"),
    ("server.ts", 'createClient(url, "sb_secret_' + "aB3_" * 10 + '")', "supabase-secret-api-key"),
    ("jobs.sh", "hf download model --token hf_" + "aB3c" * 9, "huggingface-access-token"),
    ("artifactory.json", "cmVmd" + "a" * 59, "jfrog-reference-or-api-token"),
    ("artifactory.json", "AKCp" + "b" * 69, "jfrog-reference-or-api-token"),
    ("monitoring/.env", "DD_API_KEY=" + "a1b2" * 8, "datadog-api-key-assignment"),
    ("request.log", "DD-API-KEY: " + "a1b2" * 8, "datadog-api-key-assignment"),
    ("monitoring.json", '"DATADOG_API_KEY": "' + "a1b2" * 8 + '"', "datadog-api-key-assignment"),
    (
        "database/roles.sql",
        "SCRAM-SHA-256$4096:" + "A" * 22 + "==$" + "B" * 43 + "=:" + "C" * 43 + "=",
        "postgresql-scram-verifier",
    ),
    ("bot.py", 'url="https://api.telegram.org/bot123456789:' + "Ab9_" * 8 + '/getMe"', "telegram-bot-credential"),
    ("bot/.env", "TELEGRAM_BOT_TOKEN=123456789:" + "Ab9_" * 8, "telegram-bot-credential"),
    ("redis/redis.conf", 'requirepass "Stored Literal Secret!"\n', "redis-authentication-directive"),
    ("redis/sentinel.conf", "masterauth ReplicationSecret!42\n", "redis-authentication-directive"),
    (
        "dns/rndc.key",
        'key "rndc-key" {\n  algorithm hmac-sha256;\n  secret "' + "A" * 43 + '=";\n};',
        "dns-tsig-shared-secret",
    ),
    ("rabbitmq/.erlang.cookie", "XY7ACDEFGHJKL2NPQRSTV\n", "erlang-cookie-value"),
    (
        "dns/named.conf",
        'key "ddns" { secret "' + "A" * 43 + '="; algorithm hmac-sha512; };',
        "dns-tsig-shared-secret",
    ),
    ("rabbitmq/.erlang.cookie.bak", "CustomClusterCookie123\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "cookie-value\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie.20260905", "cookie value!#_=:/\r\n", "erlang-cookie-value"),
    ("keys/identity.agekey.backup", "AGE-SECRET-KEY-1" + "Q" * 58, "age-secret-identity"),
    ("nats/account.creds.save", "SU" + "A2" * 28, "nats-nkey-seed"),
    (
        "dns/rndc.key.20260905",
        'key "rndc-key" { algorithm hmac-sha256; secret "' + "A" * 43 + '="; };',
        "dns-tsig-shared-secret",
    ),
)

NEGATIVE_CASES = (
    ("identity.txt", "age1" + "q" * 58, "age-secret-identity"),
    ("identity.txt", "AGE-SECRET-KEY-1" + "Q" * 57, "age-secret-identity"),
    ("identity.txt", "AGE-SECRET-KEY-1" + "Q" * 59, "age-secret-identity"),
    ("identity.txt", "AGE-SECRET-KEY-1" + "B" * 58, "age-secret-identity"),
    ("notes.txt", "glsa_" + "a" * 31 + "_0123abcd", "grafana-service-account-token"),
    ("notes.txt", "glsa_" + "a" * 32 + "_invalidZ", "grafana-service-account-token"),
    ("notes.txt", "glsa_" + "a" * 32 + "_0123abcde", "grafana-service-account-token"),
    ("notes.txt", "glc_your_token", "grafana-cloud-access-token"),
    ("notes.txt", "glc_" + "a" * 4097, "grafana-cloud-access-token"),
    ("notes.txt", "dop_v1_" + "a" * 31, "digitalocean-access-token"),
    ("notes.txt", "dop_v1_" + "a" * 129, "digitalocean-access-token"),
    ("notes.txt", "dop_v1_" + "g" * 64, "digitalocean-access-token"),
    ("notes.txt", "tskey-auth-AbC9dE12345", "tailscale-access-token"),
    ("notes.txt", "tskey-api-AbC9dE12345-short", "tailscale-access-token"),
    ("notes.txt", "tskey-node-AbC9dE12345-" + "x" * 32, "tailscale-access-token"),
    ("nats/account.creds", "UA" + "A2" * 27, "nats-nkey-seed"),
    ("nats/account.creds", "SU" + "A2" * 27, "nats-nkey-seed"),
    ("nats/account.creds", "SU" + "A2" * 29, "nats-nkey-seed"),
    ("nats/account.creds", "SU" + "0" * 56, "nats-nkey-seed"),
    ("bootstrap.yml", "token: a1b2c3.d4e5f6g7h8i9j0k12", "kubernetes-bootstrap-token"),
    ("bootstrap.yml", "token: A1B2C3.d4e5f6g7h8i9j0k1", "kubernetes-bootstrap-token"),
    ("bootstrap.yml", "image: a1b2c3.d4e5f6g7h8i9j0k1", "kubernetes-bootstrap-token"),
    ("server.ts", "sb_publishable_" + "a" * 40, "supabase-secret-api-key"),
    ("server.ts", "sb_secret_placeholder", "supabase-secret-api-key"),
    ("server.ts", "sb_secret_" + "a" * 256, "supabase-secret-api-key"),
    ("jobs.sh", "hf_TOKEN_PLACEHOLDER", "huggingface-access-token"),
    ("jobs.sh", "hf_" + "a" * 256, "huggingface-access-token"),
    ("artifactory.json", "cmVmd" + "a" * 58, "jfrog-reference-or-api-token"),
    ("artifactory.json", "cmVmd" + "a" * 60, "jfrog-reference-or-api-token"),
    ("artifactory.json", "AKCp" + "b" * 68, "jfrog-reference-or-api-token"),
    ("notes.txt", "checksum=" + "a1b2" * 8, "datadog-api-key-assignment"),
    ("monitoring/.env", "DD_API_KEY=" + "a1b2" * 8 + "f", "datadog-api-key-assignment"),
    ("monitoring/.env", "DD_API_KEY=${DD_API_KEY}", "datadog-api-key-assignment"),
    ("database.sql", "SCRAM-SHA-256$4096:salt$short:short", "postgresql-scram-verifier"),
    (
        "database.sql",
        "SCRAM-SHA-256$0:" + "A" * 22 + "==$" + "B" * 43 + "=:" + "C" * 43 + "=",
        "postgresql-scram-verifier",
    ),
    ("bot.py", "https://api.telegram.org.example.org/bot123456789:" + "A" * 35, "telegram-bot-credential"),
    ("bot.py", "https://api.telegram.org/bot123456789:short/getMe", "telegram-bot-credential"),
    ("notes.txt", "record=123456789:" + "A" * 35, "telegram-bot-credential"),
    ("redis.conf", "# requirepass CommentaryValue\n", "redis-authentication-directive"),
    ("redis.conf", 'requirepass ""\n', "redis-authentication-directive"),
    ("redis.conf", "masterauth ${REDIS_PASSWORD}\n", "redis-authentication-directive"),
    ("redis.conf", "requirepass\n", "redis-authentication-directive"),
    ("dns/rndc.key", 'key "rndc-key" { algorithm hmac-sha256; secret "${TSIG_KEY}"; };', "dns-tsig-shared-secret"),
    ("dns/rndc.key", 'key "rndc-key" { algorithm hmac-sha256; };', "dns-tsig-shared-secret"),
    (
        "dns/rndc.key",
        'key "public-only" { algorithm rsa-sha256; secret "' + "A" * 43 + '="; };',
        "dns-tsig-shared-secret",
    ),
    ("rabbitmq/.erlang.cookie", "${ERLANG_COOKIE}\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "  \r\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "{{ ERLANG_COOKIE }}\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "$ERLANG_COOKIE\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "cookie\tvalue\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "cookie\nvalue\n", "erlang-cookie-value"),
    ("rabbitmq/.erlang.cookie", "A" * 256, "erlang-cookie-value"),
    ("notes.txt", "XY7ACDEFGHJKL2NPQRSTV\n", "erlang-cookie-value"),
)

SOURCES = (
    ("age-secret-identity", "https://github.com/FiloSottile/age/blob/main/x25519.go"),
    ("age-secret-identity", "https://github.com/FiloSottile/age/blob/main/pq.go"),
    ("age-secret-identity", "https://github.com/FiloSottile/age/blob/main/internal/bech32/bech32.go"),
    (
        "grafana-service-account-token",
        "https://github.com/grafana/grafana/blob/main/pkg/components/satokengen/tokengen.go",
    ),
    (
        "grafana-cloud-access-token",
        "https://grafana.com/docs/learning-paths/private-data-source-connect/generate-token/",
    ),
    ("digitalocean-access-token", "https://docs.digitalocean.com/products/droplets/reference/api/droplets/"),
    ("tailscale-access-token", "https://tailscale.com/docs/reference/key-prefixes"),
    ("tailscale-access-token", "https://tailscale.com/docs/features/oauth-apps/device-provisioning"),
    ("nats-nkey-seed", "https://github.com/nats-io/nkeys"),
    ("nats-nkey-seed", "https://github.com/nats-io/nats.docs/blob/master/using-nats/nats-tools/nsc/basics.md"),
    ("kubernetes-bootstrap-token", "https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/"),
    ("supabase-secret-api-key", "https://supabase.com/docs/guides/getting-started/migrating-to-new-api-keys"),
    ("huggingface-access-token", "https://huggingface.co/docs/hub/security-tokens"),
    ("jfrog-reference-or-api-token", "https://docs.jfrog.com/user-management/docs/identity-tokens"),
    (
        "datadog-api-key-assignment",
        "https://docs.aws.amazon.com/secretsmanager/latest/userguide/mes-partner-DatadogApiKey.html",
    ),
    ("postgresql-scram-verifier", "https://doxygen.postgresql.org/scram-common_8h.html"),
    ("telegram-bot-credential", "https://core.telegram.org/bots/api#authorizing-your-bot"),
    ("redis-authentication-directive", "https://redis.io/docs/latest/operate/oss_and_stack/management/security/"),
    ("dns-tsig-shared-secret", "https://bind9.readthedocs.io/en/latest/chapter7.html#tsig"),
    ("erlang-cookie-value", "https://www.rabbitmq.com/docs/clustering#erlang-cookie"),
    ("erlang-cookie-value", "https://github.com/erlang/otp/blob/master/lib/kernel/src/auth.erl"),
)
