"""Synthetic regression cases for the audited 2.5 existing-rule replacements."""

SHA256_CRYPT = "$5$rounds=10000$salt1234$" + "A" * 43
SHA512_CRYPT = "$6$salt1234$" + "A" * 86
YESCRYPT = "$y$j9T$salt1234$" + "A" * 43
ARGON2 = "$argon2id$v=19$m=65536,t=3,p=4$c2FsdHNhbHQ$" + "A" * 43

POSITIVE_CASES = (
    ("deploy.ps1", 'ConvertTo-SecureString "RealLiteral!" -AsPlainText:$true', "powershell-plaintext-credential"),
    (
        "deploy.ps1",
        'ConvertTo-SecureString "RealLiteral!" -AsPlainText; Write-Output "done"',
        "powershell-plaintext-credential",
    ),
    (
        "deploy.ps1",
        'ConvertTo-SecureString "RealLiteral!" -AsPlainText\nWrite-Output "done"',
        "powershell-plaintext-credential",
    ),
    ("deploy.ps1", 'ConvertTo-SecureString -Force "RealLiteral!" -AsPlainText', "powershell-plaintext-credential"),
    (
        "deploy.ps1",
        'ConvertTo-SecureString -Force -AsPlainText -String "RealLiteral!"',
        "powershell-plaintext-credential",
    ),
    (
        "secret.yml",
        "kind: Secret\ndata:\n" + "                public: label\n" * 12 + "                password: c2VjcmV0IQ==\n",
        "kubernetes-secret-manifest",
    ),
    ("app.json", '{"GIUserPassword":"StoredAppPassword!"}', "application-authentication-secret"),
    ("app.xml", "<GIUserPassword>StoredAppPassword!</GIUserPassword>", "application-authentication-secret"),
    ("storage.env", "AccountKey=" + "A" * 86 + "==", "azure-storage-account-key"),
    ("storage.json", '{"AccountKey":"' + "A" * 86 + '=="}', "azure-storage-account-key"),
    ("storage.env", "SAS=sv=2024-11-04&sig=" + "A" * 43 + "=", "azure-storage-sas-token"),
    ("storage.env", "SAS=sig=" + "A" * 43 + "%3D&sp=r&sv=2024-11-04", "azure-storage-sas-token"),
    ("storage.xml", "<url>?sig=" + "A" * 43 + "%3D&amp;sv=2024-11-04</url>", "azure-storage-sas-token"),
    (
        "db.py",
        "psycopg.connect(\n host='db',\n password='StoredDbPassword!'\n)",
        "database-client-call-with-credentials",
    ),
    ("db.php", 'mysql_connect("db", "alice", "StoredDbPassword!")', "database-client-call-with-credentials"),
    ("db.pl", 'DBI->connect("DBI:mysql:db", "alice", "StoredDbPassword!")', "database-client-call-with-credentials"),
    (
        "db.rb",
        'ActiveRecord.establish_connection(password: "StoredDbPassword!")',
        "database-client-call-with-credentials",
    ),
    ("db.py", 'psycopg.connect("host=db password=StoredDbPassword!")', "database-client-call-with-credentials"),
    ("db.conf", "Server=db;Password=StoredDbPassword!;", "database-connection-string-password"),
    ("db.conf", 'Password="Stored password;with punctuation!";Data Source=db;', "database-connection-string-password"),
    ("db.conf", "Address=db;Pwd=StoredDbPassword!;", "database-connection-string-password"),
    (".docker/config.json", '{"auths":{"registry":{"auth":"YWxpY2U6c2VjcmV0"}}}', "docker-registry-auth-field"),
    ("vault.conf", "hvr." + "aB9_" * 8, "hashicorp-vault-token"),
    ("vault.conf", "hvb." + "aB9_" * 150, "hashicorp-vault-token"),
    ("vault.env", "VAULT_TOKEN=s." + "aB9_" * 8, "hashicorp-vault-token"),
    ("vault.json", '{"VAULT_TOKEN":"r.' + "aB9_" * 8 + '"}', "hashicorp-vault-token"),
    (
        "Db.java",
        'DriverManager.getConnection("jdbc:mysql://db/app", "alice", "StoredJavaPassword!")',
        "java-database-credential",
    ),
    (
        "Db.java",
        'DriverManager.getConnection("jdbc:mysql://db/app?user=alice&password=StoredJavaPassword!")',
        "java-database-credential",
    ),
    (
        ".kube/config",
        "users:\n- user:\n    token: 'StoredKubernetesToken-0123456789' # deploy",
        "kubernetes-bearer-token",
    ),
    ("kubeconfig", '{"users":[{"user":{"token":"StoredKubernetesToken-0123456789"}}]}', "kubernetes-bearer-token"),
    (".netrc", "machine db.example.test\nlogin alice\npassword StoredNetrcPassword!\n", "netrc-password"),
    ("_netrc", 'default login "Alice Example" password "Stored netrc password!"\n', "netrc-password"),
    (".netrc", 'machine host password "Stored\\"Password!" login alice\n', "netrc-password"),
    (".netrc", "machine host\n# login comment\nlogin alice\npassword Secret!\n", "netrc-password"),
    (
        ".npmrc",
        "//registry.example.test/custom/path/:_authToken=StoredRegistryToken-12345\n",
        "npm-registry-auth-token",
    ),
    (".npmrc", '//npm.pkg.github.com/:_authToken="ghp_' + "A" * 36 + '"\n', "npm-registry-auth-token"),
    (".npmrc", "_authToken=" + "a" * 40 + "\n", "npm-registry-auth-token"),
    ("hashes.txt", SHA256_CRYPT, "password-hash"),
    ("hashes.txt", SHA512_CRYPT, "password-hash"),
    ("hashes.txt", YESCRYPT, "password-hash"),
    ("hashes.txt", "$gy$j9T$salt1234$" + "A" * 43, "password-hash"),
    ("hashes.txt", "$7$" + "A" * 22 + "$" + "A" * 43, "password-hash"),
    ("hashes.txt", "$2x$04$" + "A" * 53, "password-hash"),
    ("hashes.txt", ARGON2, "password-hash"),
    (".htpasswd", "alice:$apr1$salt1234$" + "A" * 22, "password-hash"),
    ("hashes.txt", "{SSHA}" + "A" * 32, "password-hash"),
    ("hashes.txt", "{SHA}" + "A" * 27 + "=", "password-hash"),
    (
        "deploy.ps1",
        'ConvertTo-SecureString "StoredPowerShellPassword!" -AsPlainText -Force',
        "powershell-plaintext-credential",
    ),
    (
        "deploy.ps1",
        "ConvertTo-SecureString -AsPlainText -String 'StoredPowerShellPassword!' -Force",
        "powershell-plaintext-credential",
    ),
    (
        "deploy.ps1",
        "'StoredPowerShellPassword!' | ConvertTo-SecureString -AsPlainText -Force",
        "powershell-plaintext-credential",
    ),
    (
        "deploy.ps1",
        '[System.Net.NetworkCredential]::new("alice", "StoredPowerShellPassword!")',
        "powershell-plaintext-credential",
    ),
    ("server.rdp", "password 51:b:01020304aabbccdd\r\n", "rdp-password-blob"),
    ("roles.sql", "ALTER ROLE alice\n WITH PASSWORD 'StoredSqlPassword!';", "sql-account-password"),
    ("users.sql", "ALTER USER 'alice'@'%' IDENTIFIED BY 'StoredSqlPassword!';", "sql-account-password"),
    (
        "users.sql",
        "CREATE USER alice IDENTIFIED WITH caching_sha2_password BY 'StoredSqlPassword!';",
        "sql-account-password",
    ),
    ("login.sql", "ALTER LOGIN alice WITH PASSWORD = N'StoredSqlPassword!';", "sql-account-password"),
    ("twilio.json", '{"TWILIO_AUTH_TOKEN":"' + "a" * 32 + '"}', "twilio-secret"),
    ("twilio.env", "TWILIO_API_KEY_SECRET=" + "a" * 32, "twilio-secret"),
    ("twilio.env", "TWILIO_API_SECRET=" + "a" * 32, "twilio-secret"),
    (
        "unattend.xml",
        "<AutoLogon><Password><Value>StoredDeployPassword!</Value><PlainText>true</PlainText></Password></AutoLogon>",
        "unattended-install-password",
    ),
    (
        "unattend.xml",
        "<LocalAccount><Password><Value>StoredDeployPassword!</Value></Password></LocalAccount>",
        "unattended-install-password",
    ),
    (
        "unattend.xml",
        "<AdministratorPassword><Value>U3RvcmVkVmFsdWU=</Value><PlainText>false</PlainText></AdministratorPassword>",
        "unattended-install-password",
    ),
    ("etc/shadow", "root:" + SHA512_CRYPT + ":20000:0:99999:7:::", "unix-shadow-entry"),
    ("etc/shadow", "alice:!" + YESCRYPT + ":20000:0:99999:7:::", "unix-shadow-entry"),
    ("etc/shadow", "alice:" + ARGON2 + ":20000:0:99999:7:::", "unix-shadow-entry"),
    ("deploy.cmd", "net use \\\\server\\share StoredWindowsPassword! /user:alice", "windows-command-credential"),
    ("deploy.cmd", 'net user alice "Stored Windows Password!" /domain', "windows-command-credential"),
    ("deploy.cmd", 'schtasks /create /tn Test /rp "StoredWindowsPassword!"', "windows-command-credential"),
    ("deploy.cmd", "cmdkey /generic:server /user:alice /pass:StoredWindowsPassword!", "windows-command-credential"),
    ("deploy.cmd", "psexec64.exe \\\\server -u alice -p StoredWindowsPassword! cmd", "windows-command-credential"),
    (
        "wifi.xml",
        "<sharedKey><protected>false</protected><keyMaterial>StoredWifiPassword!</keyMaterial></sharedKey>",
        "wireless-cleartext-key",
    ),
    (
        "wifi.xml",
        "<w:sharedKey><w:protected>0</w:protected><w:keyMaterial>StoredWifiPassword!</w:keyMaterial></w:sharedKey>",
        "wireless-cleartext-key",
    ),
)

NEGATIVE_CASES = (
    ("deploy.ps1", 'ConvertTo-SecureString "metadata -AsPlainText string"', "powershell-plaintext-credential"),
    (
        "deploy.ps1",
        "'InputMetadata!' | ConvertTo-SecureString \"metadata -AsPlainText\"",
        "powershell-plaintext-credential",
    ),
    ("deploy.ps1", 'ConvertTo-SecureString "NotPlaintext!" -AsPlainText:$false', "powershell-plaintext-credential"),
    (
        "secret.yml",
        "kind: Secret\ndata:\n" + "                public: label\n" * 12,
        "kubernetes-secret-manifest",
    ),
    ("app.json", '{"GIUserPassword":"${APPLICATION_PASSWORD}"}', "application-authentication-secret"),
    ("app.xml", "<GIUserPassword>changeme</GIUserPassword>", "application-authentication-secret"),
    ("storage.env", "AccountKey=" + "A" * 88 + "==", "azure-storage-account-key"),
    ("storage.env", "AccountKey=" + "A" * 85 + "==", "azure-storage-account-key"),
    ("storage.env", "sv=2024-11-04&sp=r", "azure-storage-sas-token"),
    ("storage.env", "sv=2024-11-04&sig=%ZZ%ZZ%ZZ%ZZ%ZZ%ZZ", "azure-storage-sas-token"),
    ("db.php", 'mysql_connect("db.example.test")', "database-client-call-with-credentials"),
    ("db.pl", 'DBI->connect("DBI:mysql:db", "alice", $password)', "database-client-call-with-credentials"),
    ("db.py", "psycopg.connect(password=os.getenv('DB_PASSWORD'))", "database-client-call-with-credentials"),
    ("db.py", "psycopg.connect(password=None)", "database-client-call-with-credentials"),
    ("db.conf", 'Server=db;Password="";', "database-connection-string-password"),
    ("db.conf", "Server=db;Password=   ;", "database-connection-string-password"),
    ("db.conf", "Server=db;Password=${DB_PASSWORD};", "database-connection-string-password"),
    ("vault.conf", "notes=s." + "aB9_" * 8, "hashicorp-vault-token"),
    ("vault.env", "VAULT_TOKEN=${VAULT_TOKEN}", "hashicorp-vault-token"),
    ("Db.java", 'DriverManager.getConnection("jdbc:mysql://db/app", "alice")', "java-database-credential"),
    (
        "Db.java",
        'DriverManager.getConnection("jdbc:mysql://db/app", "alice", System.getenv("DB_PASSWORD"))',
        "java-database-credential",
    ),
    (
        "Db.java",
        'DriverManager.getConnection("jdbc:mysql://db/app?password=${DB_PASSWORD}")',
        "java-database-credential",
    ),
    (".kube/config", 'token: "${KUBERNETES_TOKEN}"', "kubernetes-bearer-token"),
    (".kube/config", "token: short", "kubernetes-bearer-token"),
    (".netrc", "machine first login alice\nmachine second login bob\n", "netrc-password"),
    (".netrc", "machine first login alice\n# password comment-not-a-credential\n", "netrc-password"),
    (".netrc", 'machine host login alice password ""\n', "netrc-password"),
    (".netrc", "# machine host login alice password CommentPassword\n", "netrc-password"),
    (".npmrc", "//registry.example.test/:_authToken=${NPM_TOKEN}\n", "npm-registry-auth-token"),
    (".npmrc", "//registry.example.test/:_auth=YWxpY2U6c2VjcmV0\n", "npm-registry-auth-token"),
    (".npmrc", "# //registry.example.test/:_authToken=CommentaryToken1234\n", "npm-registry-auth-token"),
    ("hashes.txt", "$argon2id$v=19$m=65536,t=3,p=4", "password-hash"),
    ("hashes.txt", "$6$salt1234$" + "A" * 43, "password-hash"),
    ("hashes.txt", "$2b$99$" + "A" * 53, "password-hash"),
    ("hashes.txt", "$apr1$salt1234$short", "password-hash"),
    ("hashes.txt", "{SSHA}someSSHAdata", "password-hash"),
    (
        "deploy.ps1",
        "$credential = New-Object System.Management.Automation.PSCredential ($user,$securePassword)",
        "powershell-plaintext-credential",
    ),
    ("deploy.ps1", "ConvertTo-SecureString $env:PASSWORD -AsPlainText -Force", "powershell-plaintext-credential"),
    ("deploy.ps1", "Read-Host -AsSecureString", "powershell-plaintext-credential"),
    ("deploy.ps1", '[Net.NetworkCredential]::new("alice", $secret)', "powershell-plaintext-credential"),
    ("server.rdp", "password 51:b:f", "rdp-password-blob"),
    ("server.rdp", "password 51:b:01020304aabbccddNOTHEX", "rdp-password-blob"),
    ("roles.sql", "ALTER ROLE alice PASSWORD NULL;", "sql-account-password"),
    ("roles.sql", "CREATE LOGIN alice WITH PASSWORD = @password;", "sql-account-password"),
    ("roles.sql", "CREATE USER alice IDENTIFIED BY '';", "sql-account-password"),
    ("twilio.env", "TWILIO_API_KEY=SK" + "a" * 32, "twilio-secret"),
    ("twilio.env", "TWILIO_AUTH_TOKEN=" + "a" * 33, "twilio-secret"),
    (
        "unattend.xml",
        "<AdministratorPassword></AdministratorPassword><Unrelated><Value>OrdinaryValue</Value></Unrelated>",
        "unattended-install-password",
    ),
    ("unattend.xml", "<Password><Value></Value></Password>", "unattended-install-password"),
    ("etc/shadow", "alice:!:20000:0:99999:7:::", "unix-shadow-entry"),
    ("etc/shadow", "alice:$6$salt$short:20000:0:99999:7:::", "unix-shadow-entry"),
    ("deploy.cmd", "net use \\\\server\\share /user:alice", "windows-command-credential"),
    ("deploy.cmd", "net user alice /domain", "windows-command-credential"),
    ("deploy.cmd", "net user alice * /domain", "windows-command-credential"),
    ("deploy.cmd", "cmdkey /generic:server /user:alice /pass:%PASSWORD%", "windows-command-credential"),
    ("deploy.cmd", 'schtasks /create /tn Test /rp ""', "windows-command-credential"),
    (
        "wifi.xml",
        "<sharedKey><protected>true</protected><keyMaterial>01020304aabbccdd</keyMaterial></sharedKey>",
        "wireless-cleartext-key",
    ),
    (
        "wifi.xml",
        "<sharedKey><protected>false</protected></sharedKey><other><keyMaterial>UnrelatedValue</keyMaterial></other>",
        "wireless-cleartext-key",
    ),
    ("wifi.xml", "<keyMaterial>UnclassifiedKeyMaterial</keyMaterial>", "wireless-cleartext-key"),
)

CLASSIFICATION_EXPECTATIONS = {
    "docker-registry-auth-field": {"severity": "high", "confidence": "medium"},
    "azure-storage-sas-token": {"confidence": "medium"},
    "aws-access-key-id": {"severity": "info", "confidence": "high"},
}

POSITIVE_CASES += (
    ("aws.txt", "AKIAABCDEFGHIJKLMNOP", "aws-access-key-id"),
    ("twilio.env", "TWILIO_API_SECRET=OpaqueStoredTwilioSecret_42!", "twilio-secret"),
    ("slack.env", "https://hooks.slack.com/services/T12345678/B12345678/abcdefghijklmnopqrstuvwx", "slack-webhook"),
    (
        "slack.env",
        "https://hooks.slack-gov.com/services/T12345678/B12345678/abcdefghijklmnopqrstuvwx",
        "slack-webhook",
    ),
    (
        "secret.yml",
        "apiVersion: v1\nkind: Secret\ndata:\n  password: c2VjcmV0cGFzcw==\n",
        "kubernetes-secret-manifest",
    ),
    (
        "secret.yml",
        "---\nkind: ConfigMap\ndata:\n  note: unrelated\n---\nkind: 'Secret'\nstringData:\n  password: 'Stored literal password!'\n",
        "kubernetes-secret-manifest",
    ),
    ("secret.yml", "data:\n  tls.key: c2VjcmV0cGFzcw==\nkind: Secret\n", "kubernetes-secret-manifest"),
    ("vpn.conf", "[Interface]\nPrivateKey=" + "A" * 43 + "= # interface\n", "wireguard-private-key"),
    ("vpn.conf", "[wireguard]\nprivate-key=" + "A" * 43 + "=\n", "wireguard-private-key"),
)

NEGATIVE_CASES += (
    ("slack.env", "https://hooks.slack.com/services/abcdefghijklmnopqrstuvwxyz", "slack-webhook"),
    (
        "slack.env",
        "https://hooks.slack.com.example.test/services/T12345678/B12345678/abcdefghijklmnopqrstuvwx",
        "slack-webhook",
    ),
    ("twilio.env", "TWILIO_API_SECRET=${TWILIO_SECRET}", "twilio-secret"),
    (
        "secret.yml",
        "kind: Secret\nmetadata:\n  name: empty\n---\nkind: ConfigMap\ndata:\n  password: c2VjcmV0cGFzcw==\n",
        "kubernetes-secret-manifest",
    ),
    ("secret.yml", "kind: Secret\nmetadata:\n  password: c2VjcmV0cGFzcw==\n", "kubernetes-secret-manifest"),
    ("secret.yml", "kind: Secret\ndata:\n  username: YWxpY2U=\n", "kubernetes-secret-manifest"),
    (
        "secret.yml",
        "kind: Secret\ndata:\n  ordinary: value\nmetadata:\n  password: c2VjcmV0cGFzcw==\n",
        "kubernetes-secret-manifest",
    ),
    (
        "secret.yml",
        "kind: Secret\n...\nkind: ConfigMap\ndata:\n  password: c2VjcmV0cGFzcw==\n",
        "kubernetes-secret-manifest",
    ),
    ("vpn.conf", "public-key=" + "A" * 43 + "=\n", "wireguard-private-key"),
    ("vpn.conf", "PrivateKey=" + "A" * 44 + "=\n", "wireguard-private-key"),
)

INTENTIONAL_BEHAVIOR_CHANGES = (
    "azure-storage-account-key no longer accepts the old malformed 90-character synthetic base64 fixture; a 512-bit key is 88 base64 characters.",
    "unix-shadow-entry and password-hash no longer accept a SHA-512-crypt fixture with only 43 digest characters; the real encoding has 86.",
    "wireless-cleartext-key requires protected=false/0 inside the same sharedKey, so the old fragment without protected is no longer claimed to be plaintext.",
    "twilio-secret excludes SK-prefixed API Key SIDs; Auth Tokens and API key secrets remain covered.",
    "npm-registry-auth-token covers _authToken only; new npm-registry-encoded-credential owns _auth and _password.",
)
