"""Russian human-assigned filenames: candidates, never verified secret content.

No fixed product filenames, extensions, or protocol attributes are translated.
Existing English predicates/excludes are preserved in full overrides. Negative
cases reject only their named rule; independent broad rules can still report.
The optional text-gate patterns below match extensionless credential aliases
and recognized backups only, not arbitrary dotted/binary extension suffixes.
"""

METADATA_CASES = (
    ("Документы/Пароли.xlsx", "password-inventory-document"),
    ("Общее/ПАРОЛЬ.txt", "password-inventory-document"),
    ("База_паролей.csv", "password-inventory-document"),
    ("Реестр учётных данных.ods", "password-inventory-document"),
    ("реестр_учетных_данных.xlsx.bak", "password-inventory-document"),
    ("Список-учётных-записей.docx", "password-inventory-document"),
    ("Учётки.txt", "password-inventory-document"),
    ("учетки.csv", "password-inventory-document"),
    ("Архив_логинов.txt", "password-inventory-document"),
    ("Доступы_VPN.xlsx", "password-inventory-document"),
    ("Данные доступа-прод.csv", "password-inventory-document"),
    ("Закрытые ключи.txt", "password-inventory-document"),
    ("Ключи_API.json", "password-inventory-document"),
    ("API-ключи-прод.yml", "password-inventory-document"),
    ("Резервные_коды.txt", "password-inventory-document"),
    ("Коды восстановления.txt", "password-inventory-document"),
    ("Резервная копия паролей.csv", "password-inventory-document"),
    ("Инвентарь_учётных_данных.docm", "password-inventory-document"),
    ("\\\\files\\share\\учётные_данные_бухгалтерия.xlsx.old", "password-inventory-document"),
    ("Экспорт_секретов_20260905.xml", "password-inventory-document"),
    ("Таблица_паролей.xlsx.20260905", "password-inventory-document"),
    ("Пароли.xlsx.bak.old", "password-inventory-document"),
    ("Учётные данные.xml", "password-inventory-document"),
    ("Логины-и-пароли.txt", "password-inventory-document"),
    ("пароли", "sensitive-configuration-file"),
    ("ПАРОЛЬ", "sensitive-configuration-file"),
    ("учётные_данные", "sensitive-configuration-file"),
    ("учетные-данные", "sensitive-configuration-file"),
    ("Секреты", "sensitive-configuration-file"),
    ("логины", "sensitive-configuration-file"),
    ("Доступы", "sensitive-configuration-file"),
    ("Данные доступа", "sensitive-configuration-file"),
    ("реестр_паролей", "sensitive-configuration-file"),
    ("закрытые_ключи", "sensitive-configuration-file"),
    ("ключи_шифрования", "sensitive-configuration-file"),
    ("ключи_доступа", "sensitive-configuration-file"),
    ("резервные_коды", "sensitive-configuration-file"),
    ("пароли_серверы.conf", "sensitive-configuration-file"),
    ("учётные_данные_склад.json.bak", "sensitive-configuration-file"),
    ("Секреты_прод.yml", "sensitive-configuration-file"),
    ("данные-доступа.properties", "sensitive-configuration-file"),
    ("пароли.20260905", "sensitive-configuration-file"),
    ("учётные_данные~", "sensitive-configuration-file"),
    ("Дамп_паролей.bin", "sensitive-name-keyword"),
    ("2016_учетные_данные_финансы.txt", "sensitive-name-keyword"),
    ("Список-учётных-записей.csv", "sensitive-name-keyword"),
    ("Экспорт_секретов.json", "sensitive-name-keyword"),
    ("Мои_доступы_серверы.xlsx", "sensitive-name-keyword"),
    ("Важные_закрытые_ключи.dat", "sensitive-name-keyword"),
    ("Важные_ключи_API.dat", "sensitive-name-keyword"),
    ("секретные-ключи.txt", "sensitive-name-keyword"),
    ("Приватный_ключ.txt", "sensitive-name-keyword"),
    ("ключи восстановления.dat", "sensitive-name-keyword"),
    ("резервные_коды.dat", "sensitive-name-keyword"),
    ("архив.логины.txt", "sensitive-name-keyword"),
    ("Письмо с паролями.msg", "sensitive-name-keyword"),
    ("реестр учёток.bin", "sensitive-name-keyword"),
    ("Сервисная учётная запись.json", "cloud-service-account-file"),
    ("служебная_учетная_запись_прод.json", "cloud-service-account-file"),
    ("Сервисный-аккаунт.json.bak", "cloud-service-account-file"),
    ("служебные-аккаунты-прод.json", "cloud-service-account-file"),
    ("учётные_данные_сервисного_аккаунта.json", "cloud-service-account-file"),
    ("Резервная копия БД.sql", "database-backup-file"),
    ("дамп_базы_данных.dump", "database-backup-file"),
    ("Бэкап-1С.zip", "database-backup-file"),
    ("Бекап_БД_склад.7z", "database-backup-file"),
    ("копия_базы_данных.sql.gz", "database-backup-file"),
    ("БД_резервная_копия.tar.gz", "database-backup-file"),
    ("Выгрузка_1С.dt", "database-backup-file"),
    ("Дамп_БД", "database-backup-file"),
    ("Резервные_копии_БД_20260905.tar.bz2", "database-backup-file"),
    ("Дамп-БД-prod.sql.bak.old", "database-backup-file"),
    ("Резервная копия УЦ/Database/Корневой УЦ.edb", "certificate-authority-database-file"),
    ("Бэкап_ADCS/Database/CA.edb.bak", "certificate-authority-database-file"),
    ("УЦ_резервная_копия/Database/Выдающий УЦ.edb", "certificate-authority-database-file"),
    ("\\\\files\\backup\\Резервные_копии_УЦ\\Database\\Корневой.edb", "certificate-authority-database-file"),
    ("Бекап_УЦ/Database/Issuer.edb.old", "certificate-authority-database-file"),
    ("Пароли LAPS.csv", "laps-password-export-file"),
    ("LAPS_пароли_серверы.xlsx", "laps-password-export-file"),
    ("LAPS_учётные_данные.json", "laps-password-export-file"),
    ("Зашифрованные_пароли_LAPS.clixml", "laps-password-export-file"),
    ("Windows-LAPS-пароли.xml", "laps-password-export-file"),
    ("Выгрузка_LAPS.ldif", "laps-password-export-file"),
    ("Экспорт_LAPS.ldf", "laps-password-export-file"),
    ("Резервная копия LAPS.json", "laps-password-export-file"),
    ("LAPS_резервные_копии.txt", "laps-password-export-file"),
    ("Пароли_Windows_LAPS.csv.bak", "laps-password-export-file"),
    ("BitLocker_ключи_восстановления.txt", "bitlocker-recovery-export-file"),
    ("Пароль восстановления BitLocker.txt", "bitlocker-recovery-export-file"),
    ("Коды восстановления BitLocker.csv", "bitlocker-recovery-export-file"),
    ("BitLocker-Пароли-восстановления-20260905.xlsx", "bitlocker-recovery-export-file"),
    ("Ключи_BitLocker.txt", "bitlocker-recovery-export-file"),
    ("BitLocker_ключ_сервера.xml.bak", "bitlocker-recovery-export-file"),
    ("Ключи_восстановления_BitLocker.pdf", "bitlocker-recovery-export-file"),
    ("ПАРОЛИ_ВОССТАНОВЛЕНИЯ_BITLOCKER.txt.old", "bitlocker-recovery-export-file"),
)

NEGATIVE_CASES = (
    ("парольная_политика.pdf", "password-inventory-document"),
    ("Секретарь.docx", "password-inventory-document"),
    ("Учет рабочего времени.xlsx", "password-inventory-document"),
    ("ключевые показатели.xlsx", "password-inventory-document"),
    ("Ключи квартиры.txt", "password-inventory-document"),
    ("Доступная среда.pdf", "password-inventory-document"),
    ("Резервная копия фотографий.zip", "password-inventory-document"),
    ("График.xlsx", "password-inventory-document"),
    ("Пароли.xlsx.example", "password-inventory-document"),
    ("Мойпароль.xlsx", "password-inventory-document"),
    ("данные-доступность.txt", "password-inventory-document"),
    ("учётность.xlsx", "password-inventory-document"),
    ("парольный", "sensitive-configuration-file"),
    ("учёт", "sensitive-configuration-file"),
    ("данные", "sensitive-configuration-file"),
    ("ключи", "sensitive-configuration-file"),
    ("секретарь", "sensitive-configuration-file"),
    ("доступ", "sensitive-configuration-file"),
    ("пароли_отдел.exe", "sensitive-configuration-file"),
    ("учётные_данные.zip", "sensitive-configuration-file"),
    ("пароли_отдел.txt.example", "sensitive-configuration-file"),
    ("ключ_от_квартиры", "sensitive-configuration-file"),
    ("учетки.xlsx", "sensitive-configuration-file"),
    ("Учёт рабочего времени", "sensitive-configuration-file"),
    ("беспарольный_вход.pdf", "sensitive-name-keyword"),
    ("Перепаролить.txt", "sensitive-name-keyword"),
    ("мойпароль.txt", "sensitive-name-keyword"),
    ("Секретариат.xlsx", "sensitive-name-keyword"),
    ("доступность.csv", "sensitive-name-keyword"),
    ("ключевые_показатели.txt", "sensitive-name-keyword"),
    ("Ключи_квартиры.txt", "sensitive-name-keyword"),
    ("Учёт_товаров.xlsx", "sensitive-name-keyword"),
    ("учётная_политика.pdf", "sensitive-name-keyword"),
    ("Общедоступные_данные.txt", "sensitive-name-keyword"),
    ("node_modules/пароли.txt", "sensitive-name-keyword"),
    ("vendor/cache/секреты.txt", "sensitive-name-keyword"),
    ("служебная_записка.json", "cloud-service-account-file"),
    ("учётная_запись.json", "cloud-service-account-file"),
    ("сервисный_отчёт.json", "cloud-service-account-file"),
    ("Сервисная учётная запись.csv", "cloud-service-account-file"),
    ("Сервисный_аккаунт.json.example", "cloud-service-account-file"),
    ("Сервисный_аккаунт_прод.exe", "cloud-service-account-file"),
    ("Резервная_копия_фотографий.zip", "database-backup-file"),
    ("Бэкап_музыки.zip", "database-backup-file"),
    ("копия_договора.pdf", "database-backup-file"),
    ("база_данных_инструкция.txt", "database-backup-file"),
    ("дамп_памяти.zip", "database-backup-file"),
    ("резервная_копия_БД_инструкция.txt", "database-backup-file"),
    ("БД_отчёт.json", "database-backup-file"),
    ("Резервная копия/Database/App.edb", "certificate-authority-database-file"),
    ("Резервная копия БД/Database/App.edb", "certificate-authority-database-file"),
    ("Бэкап_УЦ/БазаДанных/Issuer.edb", "certificate-authority-database-file"),
    ("Бэкап_УЦ/Database/Issuer.cer", "certificate-authority-database-file"),
    ("Бэкап_УЦ/Database/Issuer.edb.example", "certificate-authority-database-file"),
    ("LAPS_политика.pdf", "laps-password-export-file"),
    ("LAPS_срок_действия.csv", "laps-password-export-file"),
    ("LAPS_инструкция.txt", "laps-password-export-file"),
    ("LAPS_отчёт.csv", "laps-password-export-file"),
    ("ЛАПС_пароли.csv", "laps-password-export-file"),
    ("Пароли LAPS.csv.example", "laps-password-export-file"),
    ("BitLocker_ключевые_показатели.xlsx", "bitlocker-recovery-export-file"),
    ("BitLocker_политика.txt", "bitlocker-recovery-export-file"),
    ("BitLocker_восстановление_инструкция.pdf", "bitlocker-recovery-export-file"),
    ("Ключи_квартиры_BitLocker.txt", "bitlocker-recovery-export-file"),
    ("Битлокер_ключи.txt", "bitlocker-recovery-export-file"),
    ("Пароль восстановления BitLocker.txt.example", "bitlocker-recovery-export-file"),
)

EXTENSIONLESS_TEXT_FILENAME_PATTERNS = (
    "^(?:(?:список|списки|реестр|таблица|база|инвентарь|выгрузка|экспорт|архив|резервн(?:ая|ые)[ _-]{1,3}копи(?:я|и))[ _-]{1,3})?(?:парол(?:ь|и|ей|я|ю|е|[её]м|ям|ями|ях)|уч[её]тн(?:ые|ых|ыми|ым)[ _-]{1,3}данн(?:ые|ых|ыми|ым)|уч[её]тн(?:ая|ые|ых|ую|ой|ыми|ым)[ _-]{1,3}запис(?:ь|и|ей|ям|ями|ях)|уч[её]т(?:к[аи]|ок)|секрет(?:ы|ов)?|логин(?:ы|ов)?|доступы|данные[ _-]{1,3}доступа|(?:(?:закрыт(?:ый|ые|ых)|приватн(?:ый|ые|ых)|секретн(?:ый|ые|ых))[ _-]{1,3}ключ(?:и|ей|а|у|ом|ам|ами|ах)?|ключ(?:и|ей|а|у|ом|ам|ами|ах)?[ _-]{1,3}(?:api|апи|доступа|шифрования|восстановления)|(?:api|апи)[ _-]{1,3}ключ(?:и|ей|а|у|ом|ам|ами|ах)?)|(?:резервн(?:ые|ых)[ _-]{1,3}код(?:ы|ов)|код(?:ы|ов)[ _-]{1,3}восстановления))(?:[ _-][^\\W_][\\w (){}-]{0,94})?(?:\\.(?:bak|old|orig|backup|save)(?:\\.\\d{1,14})?|\\.\\d{8}(?:[-_]\\d{6})?|~){0,2}$",
)

TEXT_GATE_POSITIVE_CASES = (
    "пароль",
    "пароли",
    "учётные_данные",
    "учетные-данные",
    "Учётки",
    "секреты",
    "логины",
    "доступы",
    "данные доступа",
    "база_паролей",
    "реестр_учётных_данных",
    "закрытый_ключ",
    "приватные_ключи",
    "ключи_API",
    "API_ключи",
    "ключи_шифрования",
    "ключи_восстановления",
    "резервные_коды",
    "коды_восстановления",
    "Пароли_серверы.bak",
    "Учётные_данные.20260905",
)

TEXT_GATE_NEGATIVE_CASES = (
    "ключи",
    "учёт",
    "доступ",
    "секретарь",
    "данные",
    "Резервная копия фотографий",
    "пароли.exe",
    "пароли_серверы.png",
    "пароли_серверы.txt.example",
    "данные_доступность",
)
