"""Metadata 2.5 regressions: exact artifacts, contextual paths, and corrected near misses.

Rows are (path, rule_id); negatives concern only the named rule. A metadata finding
identifies a candidate and does not validate or decrypt its contents.
"""

METADATA_CASES = [
    ("users/.composer/auth.json", "composer-authentication-store"),
    ("C:\\Users\\alice\\AppData\\Roaming\\Composer\\auth.json.bak", "composer-authentication-store"),
    ("etc/pip.conf", "pip-client-configuration"),
    ("C:\\Users\\alice\\AppData\\Roaming\\pip\\pip.ini.old", "pip-client-configuration"),
    ("home/alice/.config/pypoetry/auth.toml", "poetry-authentication-store"),
    ("C:\\Users\\alice\\AppData\\Roaming\\pypoetry\\auth.toml.save", "poetry-authentication-store"),
    ("etc/openstack/clouds.yaml", "openstack-cloud-configuration"),
    ("C:\\Users\\alice\\.config\\openstack\\secure.yaml.bak", "openstack-cloud-configuration"),
    (".jupyter/jupyter_server_config.json", "jupyter-authentication-configuration"),
    ("C:\\Users\\alice\\.jupyter\\jupyter_notebook_config.py~", "jupyter-authentication-configuration"),
    ("var/lib/jenkins/secrets/master.key", "jenkins-secret-key-material"),
    ("home/user/.jenkins/secrets/master.key.old", "jenkins-secret-key-material"),
    (r"C:\Jenkins\secrets\master.key.bak", "jenkins-secret-key-material"),
    ("var/jenkins_home/secrets/master.key.20260905", "jenkins-secret-key-material"),
    ("backup/jenkins-home/secrets/master.key~", "jenkins-secret-key-material"),
    ("jenkins/secrets/hudson.util.Secret.20260905", "jenkins-secret-key-material"),
    ("secrets/com.cloudbees.plugins.credentials.SecretBytes.KEY", "jenkins-secret-key-material"),
    ("etc/gitlab/gitlab-secrets.json", "gitlab-server-secret-file"),
    ("backup/gitlab-secrets.json.bak.2", "gitlab-server-secret-file"),
    ("etc/gitea/app.ini", "gitea-server-configuration"),
    ("data/gitea/conf/app.ini", "gitea-server-configuration"),
    ("C:\\Apps\\gitea\\custom\\conf\\app.ini.old", "gitea-server-configuration"),
    ("etc/grafana/grafana.ini", "grafana-server-configuration"),
    ("grafana/conf/custom.ini.20260905", "grafana-server-configuration"),
    ("sonarqube/conf/sonar.properties", "sonarqube-server-configuration"),
    ("sonar.properties.bak", "sonarqube-server-configuration"),
    ("elasticsearch/config/elasticsearch.keystore", "elastic-stack-secure-settings"),
    ("kibana/config/kibana.keystore.bak", "elastic-stack-secure-settings"),
    ("logstash.keystore", "elastic-stack-secure-settings"),
    ("etc/rundeck/realm.properties", "rundeck-authentication-configuration"),
    ("rundeck/server/config/framework.properties.old", "rundeck-authentication-configuration"),
    ("rundeck-config.properties", "rundeck-authentication-configuration"),
    ("consul/data/serf/local.keyring", "consul-gossip-keyring"),
    ("serf/remote.keyring.bak", "consul-gossip-keyring"),
    ("home/alice/.aws/sso/cache/0123456789abcdef0123456789abcdef01234567.json", "aws-sso-token-cache"),
    ("C:\\Users\\alice\\.aws\\sso\\cache\\my-session.json.bak", "aws-sso-token-cache"),
    ("home/alice/.snowflake/connections.toml", "snowflake-client-configuration"),
    ("C:\\Users\\alice\\AppData\\Local\\snowflake\\config.toml.old", "snowflake-client-configuration"),
    ("home/alice/.databrickscfg", "databricks-client-configuration"),
    ("C:\\Users\\alice\\.databrickscfg~", "databricks-client-configuration"),
    ("home/alice/.oci/config", "oracle-cloud-client-configuration"),
    ("C:\\Users\\alice\\.oci\\config.bak", "oracle-cloud-client-configuration"),
    (".smbcredentials", "smb-client-credential-file"),
    ("etc/smbcredentials.bak", "smb-client-credential-file"),
    ("etc/davfs2/secrets", "davfs-authentication-file"),
    ("C:\\backup\\.davfs2\\secrets.old", "davfs-authentication-file"),
    ("etc/NetworkManager/system-connections/Office.nmconnection", "networkmanager-connection-profile"),
    ("Office.nmconnection.bak", "networkmanager-connection-profile"),
    ("etc/NetworkManager/system-connections/legacy-profile", "networkmanager-connection-profile"),
    ("etc/wpa_supplicant/wpa_supplicant.conf", "wpa-supplicant-configuration"),
    ("wpa_supplicant-wlan0.conf.bak", "wpa-supplicant-configuration"),
    ("etc/credstore/backup-access", "systemd-credential-store"),
    ("run/credstore.encrypted/database", "systemd-credential-store"),
    ("usr/lib/credstore/automation-token.old", "systemd-credential-store"),
    ("etc/apt/auth.conf", "apt-repository-authentication-file"),
    ("etc/apt/auth.conf.d/private-repo.conf.bak", "apt-repository-authentication-file"),
    ("etc/nix/netrc", "nix-netrc-authentication-file"),
    ("C:\\backup\\nix\\netrc.20260905", "nix-netrc-authentication-file"),
    ("etc/shadow", "unix-shadow-database-file"),
    ("etc/gshadow-", "unix-shadow-database-file"),
    ("etc/master.passwd.bak", "unix-shadow-database-file"),
    ("pwd.db", "unix-shadow-database-file"),
    (".vault-password.txt.bak", "ansible-vault-file"),
    ("vault-пароли.yaml", "ansible-vault-file"),
    ("LocalSettings.php.old", "application-credential-configuration"),
    ("logins.json.20260905", "browser-credential-database"),
    (".github/workflows/deploy.yml", "ci-runner-configuration"),
    ("etc/gitlab-runner/config.toml", "ci-runner-configuration"),
    ("jenkins/jobs/release/credentials.xml.bak", "ci-server-credential-store"),
    ("jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml", "ci-server-credential-store"),
    (".azure/msal_token_cache.bin", "cloud-cli-credential-file"),
    ("gcloud/legacy_credentials/user@example.test/adc.json", "cloud-cli-credential-file"),
    ("service-account-production.json.bak", "cloud-service-account-file"),
    (".docker/config.json.bak", "docker-registry-credentials"),
    (".dockercfg", "docker-registry-credentials"),
    ("REMINST/SMSTemp/site/variables.var.bak", "endpoint-management-variable-file"),
    ("etc/kubernetes/admin.conf", "kubernetes-client-configuration"),
    (".kube/config.20260905", "kubernetes-client-configuration"),
    ("passwords.xlsx.save", "password-inventory-document"),
    ("id_rsa.pem.bak", "ssh-private-key-file"),
    ("id_ed25519~", "ssh-private-key-file"),
    ("etc/passwd-", "unix-account-database"),
    ("etc/group", "unix-account-database"),
    (
        "AppData/Roaming/Microsoft/Protect/S-1-5-21-123/01234567-89ab-cdef-0123-456789abcdef",
        "windows-dpapi-credential-artifact",
    ),
    (
        "AppData/Local/Microsoft/Vault/01234567-89ab-cdef-0123-456789abcdef/Policy.vpol",
        "windows-dpapi-credential-artifact",
    ),
    ("exports/database.sql.bak", "configuration-data-file"),
    ("exports/site.pfx.backup", "cryptographic-key-container"),
    ("images/disk.vhdx.20260905", "virtual-machine-disk-file"),
    ("exports/ssh.pub.bak", "public-key-certificate-file"),
    ("AzureSite.publishsettings", "web-deployment-profile-file"),
    ("Properties/PublishProfiles/Production.pubxml", "web-deployment-profile-file"),
    ("Properties/PublishProfiles/Production.pubxml.user.bak", "web-deployment-profile-file"),
    ("tfplan", "terraform-state-file"),
    ("build/deploy.tfplan.save", "terraform-state-file"),
    ("home/user/.gitlab-runner/config.toml", "ci-runner-configuration"),
]

NEGATIVE_CASES = [
    ("project/auth.json", "composer-authentication-store"),
    ("composer/config.json", "composer-authentication-store"),
    ("pip.config", "pip-client-configuration"),
    ("pip.conf.example", "pip-client-configuration"),
    ("project/auth.toml", "poetry-authentication-store"),
    ("pypoetry/config.toml", "poetry-authentication-store"),
    ("project/secure.yaml", "openstack-cloud-configuration"),
    ("openstack/clouds-public.yaml", "openstack-cloud-configuration"),
    ("jupyter_server_config.json.example", "jupyter-authentication-configuration"),
    ("jupyter_lab_config.json", "jupyter-authentication-configuration"),
    ("app/master.key", "jenkins-secret-key-material"),
    ("project/secrets/master.key", "jenkins-secret-key-material"),
    ("project/secrets/master.key.bak", "jenkins-secret-key-material"),
    ("project/notjenkins/secrets/master.key", "jenkins-secret-key-material"),
    ("project/jenkins/secrets/master.key.example", "jenkins-secret-key-material"),
    ("jenkins/secrets/jenkins.model.Jenkins.crumbSalt", "jenkins-secret-key-material"),
    ("gitlab-settings.json", "gitlab-server-secret-file"),
    ("gitlab-secrets.json.example", "gitlab-server-secret-file"),
    ("project/app.ini", "gitea-server-configuration"),
    ("mygitea/conf/app.ini", "gitea-server-configuration"),
    ("app/custom.ini", "grafana-server-configuration"),
    ("grafana/conf/defaults.ini", "grafana-server-configuration"),
    ("sonar-project.properties", "sonarqube-server-configuration"),
    ("sonar.properties.example", "sonarqube-server-configuration"),
    ("trust.keystore", "elastic-stack-secure-settings"),
    ("elasticsearch.keystore.example", "elastic-stack-secure-settings"),
    ("project/framework.properties", "rundeck-authentication-configuration"),
    ("tomcat/realm.properties", "rundeck-authentication-configuration"),
    ("app/local.keyring", "consul-gossip-keyring"),
    ("serf/local.snapshot", "consul-gossip-keyring"),
    (".aws/cache/session.json", "aws-sso-token-cache"),
    (".aws/sso/cache/session.txt", "aws-sso-token-cache"),
    ("project/connections.toml", "snowflake-client-configuration"),
    ("project/config.toml", "snowflake-client-configuration"),
    ("databrickscfg", "databricks-client-configuration"),
    (".databrickscfg.example", "databricks-client-configuration"),
    ("app/config", "oracle-cloud-client-configuration"),
    (".oci/configuration", "oracle-cloud-client-configuration"),
    ("smbcredentials.example", "smb-client-credential-file"),
    ("smbcredentials.txt", "smb-client-credential-file"),
    ("app/secrets", "davfs-authentication-file"),
    ("davfs2/davfs2.conf", "davfs-authentication-file"),
    ("NetworkManager/conf.d/10-main.conf", "networkmanager-connection-profile"),
    ("Office.nmconnection.example", "networkmanager-connection-profile"),
    ("wpa_supplicant.conf.example", "wpa-supplicant-configuration"),
    ("wpa_supplicant.service", "wpa-supplicant-configuration"),
    ("docs/credstore/overview.txt", "systemd-credential-store"),
    ("var/lib/credstore/token", "systemd-credential-store"),
    ("app/auth.conf", "apt-repository-authentication-file"),
    ("etc/apt/apt.conf.d/01settings", "apt-repository-authentication-file"),
    ("app/netrc", "nix-netrc-authentication-file"),
    ("nix/nix.conf", "nix-netrc-authentication-file"),
    ("etc/passwd", "unix-shadow-database-file"),
    ("shadow.txt", "unix-shadow-database-file"),
    ("project/config.json", "docker-registry-credentials"),
    ("project/config.toml", "ci-runner-configuration"),
    ("mygitlab-runner/config.toml", "ci-runner-configuration"),
    ("exports/credentials.xml", "ci-server-credential-store"),
    ("serviceaccounting.json", "cloud-service-account-file"),
    ("workload-identity-mapping.json.example", "cloud-service-account-file"),
    ("app/admin.conf", "kubernetes-client-configuration"),
    ("app/super-admin.conf", "kubernetes-client-configuration"),
    ("id_rsa.pub", "ssh-private-key-file"),
    ("id_ed25519.pub.old", "ssh-private-key-file"),
    ("id_rsa-cert.pub", "ssh-private-key-file"),
    ("id_rsa.pub.bak", "ssh-private-key-file"),
    ("etc/shadow", "unix-account-database"),
    ("etc/pwd.db", "unix-account-database"),
    ("AppData/Microsoft/Protection/random", "windows-dpapi-credential-artifact"),
    ("XREMINST/SMSTemp/test.var", "endpoint-management-variable-file"),
    ("profile.publishsettings.example", "web-deployment-profile-file"),
    ("profile.pubxml.user.example", "web-deployment-profile-file"),
    ("planning.txt", "terraform-state-file"),
]

SOURCES = [
    ("composer-authentication-store", "https://getcomposer.org/doc/articles/authentication-for-private-packages.md"),
    ("pip-client-configuration", "https://pip.pypa.io/en/stable/topics/configuration/"),
    ("poetry-authentication-store", "https://python-poetry.org/docs/repositories/#configuring-credentials"),
    ("openstack-cloud-configuration", "https://docs.openstack.org/openstacksdk/latest/user/config/configuration.html"),
    (
        "jupyter-authentication-configuration",
        "https://jupyter-server.readthedocs.io/en/stable/operators/public-server.html",
    ),
    ("jenkins-secret-key-material", "https://www.jenkins.io/doc/developer/security/secrets/"),
    ("gitlab-server-secret-file", "https://docs.gitlab.com/development/application_secrets/"),
    ("gitea-server-configuration", "https://docs.gitea.com/administration/config-cheat-sheet/"),
    ("grafana-server-configuration", "https://grafana.com/docs/grafana/latest/administration/provisioning/"),
    (
        "sonarqube-server-configuration",
        "https://docs.sonarsource.com/sonarqube-server/server-installation/system-properties/common-properties",
    ),
    ("elastic-stack-secure-settings", "https://www.elastic.co/docs/deploy-manage/security/secure-settings"),
    (
        "rundeck-authentication-configuration",
        "https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html",
    ),
    ("consul-gossip-keyring", "https://github.com/hashicorp/consul/blob/main/agent/keyring.go"),
    ("aws-sso-token-cache", "https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso-tutorial.html"),
    (
        "snowflake-client-configuration",
        "https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-connect",
    ),
    (
        "databricks-client-configuration",
        "https://docs.databricks.com/gcp/en/dev-tools/cli/reference/configure-commands",
    ),
    ("oracle-cloud-client-configuration", "https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm"),
    ("smb-client-credential-file", "https://www.samba.org/samba/docs/current/man-html/smbclient.1.html"),
    ("davfs-authentication-file", "https://manpages.debian.org/unstable/davfs2/davfs2.conf.5.en.html"),
    (
        "networkmanager-connection-profile",
        "https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/nm-settings-keyfile.html",
    ),
    ("wpa-supplicant-configuration", "https://w1.fi/wpa_supplicant/devel/structwpa__ssid.html"),
    ("systemd-credential-store", "https://github.com/systemd/systemd/blob/main/docs/CREDENTIALS.md"),
    ("apt-repository-authentication-file", "https://manpages.debian.org/unstable/apt/apt_auth.conf.5.en.html"),
    ("nix-netrc-authentication-file", "https://nix.dev/manual/nix/2.21/command-ref/conf-file.html"),
    ("unix-shadow-database-file", "https://man7.org/linux/man-pages/man5/shadow.5.html"),
    (
        "web-deployment-profile-file",
        "https://learn.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-azure?view=visualstudio",
    ),
    (
        "web-deployment-profile-file",
        "https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-10.0",
    ),
    ("terraform-state-file", "https://developer.hashicorp.com/terraform/cli/commands/plan"),
    ("docker-registry-credentials", "https://docs.docker.com/reference/cli/docker/login/"),
    ("ci-runner-configuration", "https://docs.gitlab.com/runner/configuration/advanced-configuration/"),
    ("unix-account-database", "https://man7.org/linux/man-pages/man5/passwd.5.html"),
]
