"""Metadata regression fixtures for the default-pack 2.4 credential artifacts.

Negative cases suppress only their named rule, not other default-pack rules.
A metadata report identifies an artifact candidate and does not prove its contents.
"""

METADATA_CASES = [
    (".mylogin.cnf", "mysql-login-path-file"),
    ("profiles/user/.mylogin.cnf.bak.2", "mysql-login-path-file"),
    ("C:\\Users\\alice\\AppData\\Roaming\\MySQL\\.mylogin.cnf~", "mysql-login-path-file"),
    (".pg_service.conf", "postgresql-service-configuration"),
    ("etc/postgresql/pg_service.conf.old", "postgresql-service-configuration"),
    ("C:\\Users\\alice\\AppData\\Roaming\\postgresql\\.pg_service.conf", "postgresql-service-configuration"),
    ("home/alice/.m2/settings.xml", "maven-authentication-settings"),
    ("C:\\Users\\alice\\.m2\\settings.xml.bak", "maven-authentication-settings"),
    ("opt/apache-maven-3.9.9/conf/settings.xml", "maven-authentication-settings"),
    ("exports/settings-security.xml.20260905", "maven-authentication-settings"),
    ("src/service/NuGet.Config", "nuget-package-source-configuration"),
    ("C:\\Users\\alice\\AppData\\Roaming\\NuGet\\NuGet.Config.old", "nuget-package-source-configuration"),
    ("home/alice/.gradle/gradle.properties", "gradle-build-properties"),
    ("src/application/gradle.properties.save", "gradle-build-properties"),
    ("rclone.conf", "rclone-remote-configuration"),
    ("home/alice/.rclone.conf.bak", "rclone-remote-configuration"),
    ("C:\\Users\\alice\\AppData\\Roaming\\rclone\\rclone.conf~", "rclone-remote-configuration"),
    ("etc/resticprofile/profiles.toml", "resticprofile-backup-configuration"),
    ("C:\\ProgramData\\resticprofile\\profiles.yaml.bak", "resticprofile-backup-configuration"),
    ("etc/restic/profiles.conf", "resticprofile-backup-configuration"),
    ("home/alice/.config/gh/hosts.yml", "github-cli-authentication-file"),
    ("C:\\Users\\alice\\AppData\\Roaming\\gh\\hosts.yml.old", "github-cli-authentication-file"),
    ("credentials.tfrc.json", "terraform-cli-credential-store"),
    ("C:\\Users\\alice\\AppData\\Roaming\\terraform.d\\credentials.tfrc.json.bak", "terraform-cli-credential-store"),
    ("home/alice/.cargo/credentials", "cargo-registry-credential-store"),
    ("C:\\Users\\alice\\.cargo\\credentials.toml.old", "cargo-registry-credential-store"),
    ("home/alice/.cargo/credentials.bak", "cargo-registry-credential-store"),
    ("run/user/1000/containers/auth.json", "container-registry-auth-store"),
    ("C:\\Users\\alice\\.config\\containers\\auth.json.bak", "container-registry-auth-store"),
    ("var/run/secrets/kubernetes.io/serviceaccount/token", "kubernetes-service-account-token-file"),
    ("C:\\var\\run\\secrets\\kubernetes.io\\serviceaccount\\token.bak", "kubernetes-service-account-token-file"),
    (".vault-token", "hashicorp-vault-token-file"),
    ("home/alice/.vault-token.old", "hashicorp-vault-token-file"),
]

NEGATIVE_CASES = [
    (".mylogin.cnf.example", "mysql-login-path-file"),
    (".mylogin.cnf.php", "mysql-login-path-file"),
    ("mylogin.cnf", "mysql-login-path-file"),
    ("pg_service.conf.sample", "postgresql-service-configuration"),
    ("pg_service.confused", "postgresql-service-configuration"),
    ("assets/settings.xml", "maven-authentication-settings"),
    (".m2/repository/settings.xml", "maven-authentication-settings"),
    ("apache-maven-3.9.9/conf/settings.xml.example", "maven-authentication-settings"),
    ("NuGet.Config.template", "nuget-package-source-configuration"),
    ("packages.config", "nuget-package-source-configuration"),
    ("gradle-wrapper.properties", "gradle-build-properties"),
    ("gradle.properties.example", "gradle-build-properties"),
    ("rclone.conf.example", "rclone-remote-configuration"),
    ("rclone.configuration", "rclone-remote-configuration"),
    ("browser/profiles.toml", "resticprofile-backup-configuration"),
    ("resticprofiled/profiles.yaml", "resticprofile-backup-configuration"),
    ("resticprofile/profiles.yaml.example", "resticprofile-backup-configuration"),
    ("inventory/hosts.yml", "github-cli-authentication-file"),
    ("gh/config.yml", "github-cli-authentication-file"),
    ("gh/hosts.yml.template", "github-cli-authentication-file"),
    ("credentials.tfrc.json.example", "terraform-cli-credential-store"),
    ("credentials.json", "terraform-cli-credential-store"),
    ("cargo/credentials.toml", "cargo-registry-credential-store"),
    (".cargo/config.toml", "cargo-registry-credential-store"),
    (".cargo/credentials.toml.example", "cargo-registry-credential-store"),
    ("service/auth.json", "container-registry-auth-store"),
    ("mycontainers/auth.json", "container-registry-auth-store"),
    ("containers/auth.json.sample", "container-registry-auth-store"),
    ("serviceaccount/token", "kubernetes-service-account-token-file"),
    ("secrets/kubernetes.io/serviceaccount/ca.crt", "kubernetes-service-account-token-file"),
    ("secrets/kubernetes.io/serviceaccount/tokenizer", "kubernetes-service-account-token-file"),
    (".vault-token.example", "hashicorp-vault-token-file"),
    (".vault-token.json", "hashicorp-vault-token-file"),
]

SOURCES = [
    "https://dev.mysql.com/doc/refman/8.0/en/mysql-config-editor.html",
    "https://www.postgresql.org/docs/16/libpq-pgservice.html",
    "https://maven.apache.org/settings.html",
    "https://maven.apache.org/guides/mini/guide-encryption.html",
    "https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file",
    "https://docs.gradle.org/current/userguide/build_environment.html",
    "https://docs.gradle.org/current/userguide/supported_repository_protocols.html",
    "https://rclone.org/docs/#config-string",
    "https://creativeprojects.github.io/resticprofile/configuration/path/index.html",
    "https://creativeprojects.github.io/resticprofile/reference/profile/index.html",
    "https://cli.github.com/manual/gh_auth_login",
    "https://github.com/cli/cli/blob/trunk/internal/config/config.go",
    "https://developer.hashicorp.com/terraform/cli/commands/login",
    "https://doc.rust-lang.org/cargo/reference/config.html#credentials",
    "https://docs.podman.io/en/v5.0.1/markdown/podman-login.1.html",
    "https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/",
    "https://developer.hashicorp.com/vault/docs/commands/token-helper",
]
