"""Positive and negative native rule-pack 2.5 content fixtures; synthetic secrets only."""

CONTENT_CASES = [
    ("NuGet.Config", '<add key="ClearTextPassword" value="NuGetFixturePassword!" />', "nuget-cleartext-credential"),
    ("nuget.config", "<add value='NuGetFixturePassword!' key=\"ClearTextPassword\" />", "nuget-cleartext-credential"),
    (".npmrc", "//registry.internal/:_auth=YWxpY2U6Rml4dHVyZVBhc3M=\n", "npm-registry-encoded-credential"),
    ("backups/.npmrc.old", "_password=Rml4dHVyZSE=\n", "npm-registry-encoded-credential"),
    (
        "kafka/server.jaas",
        'org.apache.kafka.common.security.plain.PlainLoginModule required\nuser_monitor="JaAsAccountFixture!";',
        "kafka-jaas-credential",
    ),
    (
        "client.properties",
        'sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="alice" password="KafkaFixture!";',
        "kafka-jaas-credential",
    ),
    ("etc/nslcd.conf", "bindpw LdapBindFixture!\n", "ldap-bind-credential"),
    ("ldap/config.conf", "rootpwmodpw LdapBindFixture!\n", "ldap-bind-credential"),
    ("etc/sssd/sssd.conf", "ldap_default_authtok = SssdBindFixture!", "sssd-ldap-auth-token"),
    ("etc/sssd/sssd.conf", 'ldap_default_authtok = "Account Password!"', "sssd-ldap-auth-token"),
    ("snmpd.conf", "rwcommunity SnmpFixtureCommunity 192.0.2.0/24", "snmp-community-directive"),
    ("snmpd.conf", "com2sec -Cn ops monitor default SnmpFixtureCommunity", "snmp-community-directive"),
    ("snmp.conf", "defCommunity public", "snmp-community-directive"),
    ("redis/users.acl", "user monitor on >RedisAclFixture! ~* +@read", "redis-acl-credential"),
    (
        "redis/users.acl",
        "user alice on #a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2 ~* +@all",
        "redis-acl-credential",
    ),
    ("redis/commands.txt", "ACL SETUSER alice on >CommandFixture! +get", "redis-acl-credential"),
    ("etc/ipsec.secrets", '@alice @gateway : PSK "Ipsec Fixture Secret!"', "ipsec-shared-secret-entry"),
    ("etc/ipsec.secrets", ': EAP "EapAccountFixture!"', "ipsec-shared-secret-entry"),
    ("etc/wpa_supplicant.conf", 'network={\n psk="WirelessFixture!"\n}\n', "wireless-psk-configuration"),
    ("WiFi.nmconnection", "[wifi-security]\npsk=Wireless Fixture Password\n", "wireless-psk-configuration"),
    (
        "etc/wpa_supplicant.conf",
        "psk=abababababababababababababababababababababababababababababababab",
        "wireless-psk-configuration",
    ),
    ("etc/rsyncd.secrets", "backupuser:RsyncFixturePassword!\n", "rsync-secrets-entry"),
    ("rsync.secrets.old", "alice:A\n", "rsync-secrets-entry"),
    ("users/.curlrc", 'user = "alice:CurlFixture!"\n', "curl-config-credential"),
    ("_curlrc.old", "proxy-user = proxy:CurlProxyFixture!\n", "curl-config-credential"),
    (
        "squid.conf",
        "cache_peer proxy.example.test parent 3128 0 login=alice:ProxyFixture!",
        "squid-parent-proxy-credential",
    ),
    (
        "squid.conf",
        "cache_peer proxy.example.test parent 3128 0 login=*:SharedProxyFixture!",
        "squid-parent-proxy-credential",
    ),
    (
        "jupyter_server_config.py",
        'c.ServerApp.password = "sha1:abababababab:c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1"',
        "jupyter-legacy-password-hash",
    ),
    (
        "jupyter_notebook_config.json",
        '{"password":"sha1:abababababab:c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1"}',
        "jupyter-legacy-password-hash",
    ),
    (
        "servicebus.config",
        "Endpoint=sb://bus.example.test/;SharedAccessKeyName=send;SharedAccessKey=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=",
        "azure-servicebus-shared-access-key",
    ),
    (
        "bus.log",
        "SharedAccessSignature sr=https%3A%2F%2Fbus.example.test%2Fqueue&sig=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%3D&se=1900000000&skn=send",
        "azure-servicebus-sas-token",
    ),
    (
        "bus.log",
        "SharedAccessSignature se=1900000000&sig=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%3D&sr=sb%3A%2F%2Fbus.example.test",
        "azure-servicebus-sas-token",
    ),
    (
        "application_default_credentials.json",
        '"refresh_token": "1//aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_"',
        "google-oauth-refresh-token",
    ),
    (
        "client.py",
        "refresh_token='1//aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_'",
        "google-oauth-refresh-token",
    ),
    (
        "gitlab-variables.json",
        '{"variable_type":"env_var","key":"DEPLOY_PASSWORD","value":"StructuredFixture!"}',
        "structured-sensitive-key-value",
    ),
    (
        "collection.postman_environment.json",
        '{"value":"StructuredFixture!","enabled":true,"key":"api_token","type":"secret"}',
        "structured-sensitive-key-value",
    ),
    ("pod.json", '{"name":"SERVICE_CLIENT_SECRET","value":"StructuredFixture!"}', "structured-sensitive-key-value"),
    ("request.http", "X-Api-Key: HttpHeaderFixture123!", "http-sensitive-auth-header"),
    ("request.rest", '"X-Vault-Token": "s.LegacyVaultFixture123"', "http-sensitive-auth-header"),
    ("headers.json", "Private-Token: LegacyGitlabFixture123", "http-sensitive-auth-header"),
    (
        "users/.kube/config",
        "client-key-data: LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t",
        "kubernetes-client-key-data",
    ),
    (
        "kube.json",
        '"client-key-data": "LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t"',
        "kubernetes-client-key-data",
    ),
    ("inventory.ini", "host ansible_user=alice ansible_ssh_pass=InventoryFixture!", "ansible-inventory-password"),
    ("group_vars/all.yml", "ansible_become_pass: 'Become Fixture!'", "ansible-inventory-password"),
    (
        "downloads.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "downloads.json",
        '{"url":"https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=abababababababababababababababababababababababababababababababab"}',
        "aws-presigned-url",
    ),
    (
        "production.postman_collection.json",
        '{"type":"apikey","apikey":[{"key":"key","value":"Custom-Header"},{"key":"value","value":"PostmanFixture!","type":"string"}]}',
        "postman-authentication-value",
    ),
    (
        "production.postman_collection.json",
        '{"bearer":[{"value":"PostmanFixture!","key":"token","type":"string"}],"type":"bearer"}',
        "postman-authentication-value",
    ),
    (
        "requests/login.bru",
        "auth:apikey {\n key: X-Service-Credential\n value: BrunoFixture!\n placement: header\n}",
        "bruno-api-key-auth-value",
    ),
    (
        "anthropic.env",
        "sk-ant-api03-aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_",
        "anthropic-api-credential",
    ),
    (
        "admin.json",
        "sk-ant-admin01-aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_",
        "anthropic-api-credential",
    ),
    (
        "compliance.json",
        "sk-ant-api01-aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_",
        "anthropic-api-credential",
    ),
    ("rsyncd.secrets", "alice:Rsync:Colon:Password!", "rsync-secrets-entry"),
    (
        "jaas.conf",
        'org.apache.kafka.common.security.plain.PlainLoginModule required user_alice="KafkaAliceFixture!" user_bob="KafkaBobFixture!";',
        "kafka-jaas-credential",
    ),
    (
        "requests/login.bru",
        "auth:apikey {\n key: {{HEADER_NAME}}\n value: BrunoLiteralSecret!\n placement: header\n}",
        "bruno-api-key-auth-value",
    ),
    (
        "kafka/client.properties",
        'org.apache.kafka.common.security.plain.PlainLoginModule required username="${ACCOUNT_NAME}" password="KafkaLiteralSecret!";',
        "kafka-jaas-credential",
    ),
    (".npmrc", "_auth=YWxpY2U6Rml4dHVyZVBhc3M=", "npm-registry-encoded-credential"),
    (
        "variables.json",
        '{"description":"deployment","value":"CasePreservedSecret!","masked":true,"key":"PROD_DATABASE_PASSWORD","protected":false}',
        "structured-sensitive-key-value",
    ),
    (
        "variables.json",
        '{"key":"CLIENT_SECRET","value":"Quoted\\\\Value\\"Fixture!"}',
        "structured-sensitive-key-value",
    ),
    (
        "collection.json",
        '{"type":"bearer","bearer":[{"key":"token","value":"BearerStoredLiteral!"}]}',
        "postman-authentication-value",
    ),
    ("nslcd.conf", "rootpwmodpw AnotherLdapBindFixture!", "ldap-bind-credential"),
    (
        "download.log",
        "https://bucket.example.test/file?X-Amz-Signature=abababababababababababababababababababababababababababababababab&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Date=20260905T120000Z&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Algorithm=AWS4-HMAC-SHA256",
        "aws-presigned-url",
    ),
]

NEGATIVE_CASES = [
    ("nuget.config", '<add key="Username" value="ordinaryuser" />', "nuget-cleartext-credential"),
    ("nuget.config", '<add key="ClearTextPassword" value="%NUGET_PASSWORD%" />', "nuget-cleartext-credential"),
    ("nuget.config", '<add key="ClearTextPassword" /><add value="OtherSettingValue" />', "nuget-cleartext-credential"),
    (".npmrc", "//registry.internal/:_auth=${NPM_AUTH}\n", "npm-registry-encoded-credential"),
    (".npmrc", "_password=abc\n", "npm-registry-encoded-credential"),
    ("notes.txt", "_auth=YWxpY2U6Rml4dHVyZVBhc3M=\n", "npm-registry-encoded-credential"),
    (
        "client.properties",
        'org.apache.kafka.common.security.plain.PlainLoginModule required password="${KAFKA_PASSWORD}";',
        "kafka-jaas-credential",
    ),
    (
        "client.properties",
        'org.apache.kafka.common.security.plain.PlainLoginModule required username="alice";',
        "kafka-jaas-credential",
    ),
    ("client.properties", 'other.Module required user_monitor="NotKafkaContext";', "kafka-jaas-credential"),
    ("etc/nslcd.conf", "# bindpw CommentFixture!\n", "ldap-bind-credential"),
    ("etc/nslcd.conf", "bindpw ${LDAP_PASSWORD}\n", "ldap-bind-credential"),
    ("ldap/config.ldif", "olcBindDN: cn=bind,dc=example,dc=test\n", "ldap-bind-credential"),
    ("etc/sssd/sssd.conf", "ldap_default_authtok_type = password", "sssd-ldap-auth-token"),
    ("etc/sssd/sssd.conf", "ldap_default_authtok = ${LDAP_SECRET}", "sssd-ldap-auth-token"),
    ("snmpd.conf", "# rocommunity CommentCommunity", "snmp-community-directive"),
    ("snmpd.conf", "rocommunity ${SNMP_COMMUNITY}", "snmp-community-directive"),
    ("snmpd.conf", "rouser monitor authPriv", "snmp-community-directive"),
    ("redis/users.acl", "user default on nopass ~* +@all", "redis-acl-credential"),
    ("redis/users.acl", "user alice on >${REDIS_PASSWORD} ~*", "redis-acl-credential"),
    (
        "redis/users.acl",
        "user alice on #a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2a1b2 ~*",
        "redis-acl-credential",
    ),
    ("redis/users.acl", "# user alice on >CommentSecret", "redis-acl-credential"),
    ("etc/ipsec.secrets", ": RSA server-key.pem", "ipsec-shared-secret-entry"),
    ("etc/ipsec.secrets", '# @alice : PSK "CommentSecret!"', "ipsec-shared-secret-entry"),
    ("etc/ipsec.secrets", ': PSK "${IPSEC_PSK}"', "ipsec-shared-secret-entry"),
    ("settings.txt", 'psk="WirelessFixture!"', "wireless-psk-configuration"),
    ("etc/wpa_supplicant.conf", '# psk="CommentSecret!"', "wireless-psk-configuration"),
    ("WiFi.nmconnection", "psk=${WIFI_PASSWORD}\n", "wireless-psk-configuration"),
    ("WiFi.nmconnection", "psk-flags=1\n", "wireless-psk-configuration"),
    ("notes.txt", "backupuser:RsyncFixturePassword!", "rsync-secrets-entry"),
    ("rsyncd.secrets", "alice:", "rsync-secrets-entry"),
    ("rsyncd.secrets", "# alice:CommentSecret", "rsync-secrets-entry"),
    ("rsyncd.secrets", "alice:${RSYNC_PASSWORD}", "rsync-secrets-entry"),
    ("users/.curlrc", "user = alice", "curl-config-credential"),
    ("users/.curlrc", "user = alice:", "curl-config-credential"),
    ("users/.curlrc", 'user = "alice:${CURL_PASSWORD}"', "curl-config-credential"),
    ("notes.txt", 'user = "alice:CurlFixture!"', "curl-config-credential"),
    ("squid.conf", "cache_peer proxy.example.test parent 3128 0 login=PASSTHRU", "squid-parent-proxy-credential"),
    (
        "squid.conf",
        "cache_peer proxy.example.test parent 3128 0 login=alice:${PROXY_PASSWORD}",
        "squid-parent-proxy-credential",
    ),
    ("squid.conf", "# cache_peer proxy parent 3128 0 login=alice:Comment!", "squid-parent-proxy-credential"),
    ("notes.txt", "sha1:abababababab:c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1", "jupyter-legacy-password-hash"),
    ("jupyter_server_config.py", "sha1:abcd:c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1", "jupyter-legacy-password-hash"),
    ("servicebus.config", "SharedAccessKeyName=ordinary-name", "azure-servicebus-shared-access-key"),
    ("servicebus.config", "SharedAccessKey=${BUS_KEY}", "azure-servicebus-shared-access-key"),
    (
        "servicebus.config",
        "SharedAccessKey=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=",
        "azure-servicebus-shared-access-key",
    ),
    (
        "bus.log",
        "SharedAccessSignature sr=https%3A%2F%2Fbus.example.test&sig=short&se=1900000000",
        "azure-servicebus-sas-token",
    ),
    ("bus.log", "SharedAccessSignature sr=https%3A%2F%2Fbus.example.test&se=1900000000", "azure-servicebus-sas-token"),
    ("client.json", '"refresh_token":"${REFRESH_TOKEN}"', "google-oauth-refresh-token"),
    (
        "client.json",
        '"access_token":"1//aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_"',
        "google-oauth-refresh-token",
    ),
    ("client.json", '"refresh_token":"1//short"', "google-oauth-refresh-token"),
    ("vars.json", '[{"key":"PASSWORD"},{"value":"DifferentObject"}]', "structured-sensitive-key-value"),
    ("vars.json", '{"key":"PASSWORD","nested":{"value":"NestedOtherObject"}}', "structured-sensitive-key-value"),
    ("vars.json", '{"key":"BASE_URL","value":"https://example.test"}', "structured-sensitive-key-value"),
    ("vars.json", '{"key":"PASSWORD","value":"{{PASSWORD}}"}', "structured-sensitive-key-value"),
    ("vars.json", '{"key":"PASSWORD","value":""}', "structured-sensitive-key-value"),
    ("vars.json", '{"key":"PASSWORD","value":"none"}', "structured-sensitive-key-value"),
    ("request.http", "X-Api-Key: ${API_KEY}", "http-sensitive-auth-header"),
    ("request.http", "X-Api-Key: {{API_KEY}}", "http-sensitive-auth-header"),
    ("request.http", "X-Request-Id: CorrelationIdentifier123", "http-sensitive-auth-header"),
    (
        "kube.json",
        '"client-certificate-data":"LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t"',
        "kubernetes-client-key-data",
    ),
    ("kube.json", '"client-key-data":"${CLIENT_KEY}"', "kubernetes-client-key-data"),
    ("kube.json", '"client-key-data":"short"', "kubernetes-client-key-data"),
    ("inventory.ini", "ansible_ssh_pass={{vault_password}}", "ansible-inventory-password"),
    ("group_vars/all.yml", "ansible_become_pass: !vault |", "ansible-inventory-password"),
    ("inventory.ini", "notansible_ssh_pass=NotARealSetting!", "ansible-inventory-password"),
    (
        "downloads.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&unrelated=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "downloads.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-SignedHeaders=host&X-Amz-Signature=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "downloads.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=ababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "production.postman_collection.json",
        '{"type":"apikey","apikey":[{"key":"value","value":"{{API_KEY}}"}]}',
        "postman-authentication-value",
    ),
    (
        "production.postman_collection.json",
        '{"type":"apikey","apikey":[{"key":"value"},{"value":"DifferentObject"}]}',
        "postman-authentication-value",
    ),
    (
        "production.postman_collection.json",
        '{"type":"apikey","apikey":[{"key":"key","value":"Custom-Header"}]}',
        "postman-authentication-value",
    ),
    (
        "requests/login.bru",
        "auth:apikey {\n key: X-Service-Credential\n value: {{API_KEY}}\n}",
        "bruno-api-key-auth-value",
    ),
    ("requests/login.bru", "headers {\n value: NotAuthContext\n}", "bruno-api-key-auth-value"),
    ("notes.txt", "auth:apikey {\n value: BrunoFixture!\n}", "bruno-api-key-auth-value"),
    ("admin.json", "sk-ant-admin01-placeholder", "anthropic-api-credential"),
    (
        "admin.json",
        "sk-ant-api03-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "anthropic-api-credential",
    ),
    (
        "admin.json",
        "prefixsk-ant-api03-aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_aB9_",
        "anthropic-api-credential",
    ),
    ("headers.txt", "Unrelated-X-Api-Key: GenuineButWrongHeader123!", "http-sensitive-auth-header"),
    ("ansible.yml", "ansible_become_pass:    !vault |", "ansible-inventory-password"),
    (
        "variables.json",
        '[{"key":"password","value":null},{"key":"label","value":"CrossObjectLeak123!"}]',
        "structured-sensitive-key-value",
    ),
    (
        "variables.json",
        '{"key":"password","nested":{"value":"NestedNotSameRecord!"}}',
        "structured-sensitive-key-value",
    ),
    (
        "postman.json",
        '{"apikey":[{"key":"value","value":"FixtureApi123!"}],"type":"bearer"}',
        "postman-authentication-value",
    ),
    (".curlrc", "user=alice:   ", "curl-config-credential"),
    ("nslcd.conf", "olcBindPW: NotAnActualNslcdDirective!", "ldap-bind-credential"),
    (".npmrc", "_auth=changeme", "npm-registry-encoded-credential"),
    (".npmrc", "_password=redacted", "npm-registry-encoded-credential"),
    ("variables.json", '{"key":"password","value":"{{PASSWORD}}"}', "structured-sensitive-key-value"),
    ("variables.json", '{"key":"password","value":"${PASSWORD}"}', "structured-sensitive-key-value"),
    ("variables.json", '{"key":"password","value":""}', "structured-sensitive-key-value"),
    (
        "variables.json",
        '{"key":"name","value":"{\\"key\\":\\"password\\"}","label":"value"}',
        "structured-sensitive-key-value",
    ),
    ("variables.json", '{"key":"password","value":{"nested":"NotLiteralScalar!"}}', "structured-sensitive-key-value"),
    ("variables.json", '[{"key":"password"},{"value":"CrossRecord!"}]', "structured-sensitive-key-value"),
    (
        "request.bru",
        "auth:apikey {\n key: X-Header\n}\nvars:pre-request {\n value: DifferentBlock!\n}",
        "bruno-api-key-auth-value",
    ),
    ("request.bru", "auth:apikey {\n key: {{HEADER_NAME}}\n value: {{TOKEN}}\n}", "bruno-api-key-auth-value"),
    (
        "download.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "download.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&NotX-Amz-Signature=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "download.log",
        "https://bucket.example.test/file?Other-X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "download.log",
        "https://bucket.example.test/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAABCDEFGHIJKLMNOP%2F20260905%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260905T120000Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host\nhttps://second.example.test/?X-Amz-Signature=abababababababababababababababababababababababababababababababab",
        "aws-presigned-url",
    ),
    (
        "postman.json",
        '{"apikey":[{"key":"value","value":"{{API_KEY}}"}],"type":"apikey"}',
        "postman-authentication-value",
    ),
    ("postman.json", '{"type":"apikey","apikey":[{"key":"value","value":""}]}', "postman-authentication-value"),
]

# Independent ownership/malformed-input review, not just representative positives.
CONTENT_CASES += [
    ("kubeconfig", "client-key-data: " + "A" * 78 + "==", "kubernetes-client-key-data"),
    ("kubeconfig", "client-key-data: " + "A" * 79 + "=", "kubernetes-client-key-data"),
    (
        "NuGet.Config",
        '<add\n key="ClearTextPassword"\n value="MultilineNugetSecret!" />',
        "nuget-cleartext-credential",
    ),
    (
        "NuGet.Config",
        '<add value="NugetWith&gt;Punctuation!"\n key="ClearTextPassword" />',
        "nuget-cleartext-credential",
    ),
    (
        "kafka/client.jaas",
        'org.apache.kafka.common.security.plain.PlainLoginModule required username="account;with;semicolons" password="Real;Secret!";',
        "kafka-jaas-credential",
    ),
    (
        "kafka/client.jaas",
        'org.apache.kafka.common.security.plain.PlainLoginModule required\n// comment\nusername="alice" /* comment */ password="Quoted\\"Secret!";',
        "kafka-jaas-credential",
    ),
    (
        "postman.json",
        '{"type":"bearer","bearer":[{"key":"token","value":"RealBearerLiteral!"}]}',
        "postman-authentication-value",
    ),
    (
        "request.bru",
        "auth:apikey {\n" + "                key: label\n" * 12 + " value: IndentedLiteralSecret!\n}",
        "bruno-api-key-auth-value",
    ),
]

NEGATIVE_CASES += [
    (
        "bus.log",
        "SharedAccessSignature sr=https%3A%2F%2Fbus.example.test&se=1900000000&skn=send&other-sig=" + "A" * 43 + "%3D",
        "azure-servicebus-sas-token",
    ),
    (
        "bus.log",
        "SharedAccessSignature sr=https%3A%2F%2Fbus.example.test&sig=" + "A" * 43 + "%3D&skn=send&other-se=1900000000",
        "azure-servicebus-sas-token",
    ),
    ("kubeconfig", "client-key-data: " + "A" * 81, "kubernetes-client-key-data"),
    ("kubeconfig", "client-key-data: " + "A" * 80 + "=", "kubernetes-client-key-data"),
    ("variables.json", '{"key":"PASSWORD","value":"   "}', "structured-sensitive-key-value"),
    ("variables.json", '{"key":"PASSWORD","value":"\\t\\u0020"}', "structured-sensitive-key-value"),
    (
        "postman.json",
        '{"type":"apikey","apikey":[{"key":"value","value":"   "}]}',
        "postman-authentication-value",
    ),
    ("NuGet.Config", '<add data-key="ClearTextPassword" value="WrongAttribute!"/>', "nuget-cleartext-credential"),
    ("NuGet.Config", '<add key="ClearTextPassword" data-value="WrongAttribute!"/>', "nuget-cleartext-credential"),
    ("NuGet.Config", '<add label=\'key="ClearTextPassword"\' value="QuotedMetadata!"/>', "nuget-cleartext-credential"),
    ("NuGet.Config", '<add key="ClearTextPassword" value="   "/>', "nuget-cleartext-credential"),
    (
        "kafka/client.jaas",
        "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"not password='MetadataOnly!'\";",
        "kafka-jaas-credential",
    ),
    (
        "kafka/client.jaas",
        'org.apache.kafka.common.security.plain.PlainLoginModule required\n// password="CommentMetadata!"\nusername="alice";',
        "kafka-jaas-credential",
    ),
    (
        "kafka/client.jaas",
        'org.apache.kafka.common.security.plain.PlainLoginModule required username="alice";\npassword="OutsideModule!";',
        "kafka-jaas-credential",
    ),
    (
        "postman.json",
        '{"type":"apikey","apikey":[{"key":"token","value":"UnusedFieldLiteral!"}]}',
        "postman-authentication-value",
    ),
    (
        "postman.json",
        '{"bearer":[{"key":"value","value":"UnusedFieldLiteral!"}],"type":"bearer"}',
        "postman-authentication-value",
    ),
    (
        "request.bru",
        "auth:apikey {\n" + "                key: label\n" * 12 + "}\n",
        "bruno-api-key-auth-value",
    ),
]

METADATA_CASES = [
    ("project/http-client.private.env.json", "api-client-private-environment-file"),
    ("exports/production.postman_environment.json", "api-client-private-environment-file"),
    ("exports/team.postman_collection.json", "api-client-request-collection"),
    ("exports/Insomnia_2026-09-05.json", "api-client-request-collection"),
    ("requests/collection.bru", "api-client-request-collection"),
    ("requests/bruno.json", "api-client-request-collection"),
    ("project/.insomnia/requests/req_123.yml", "api-client-request-collection"),
]

METADATA_NEGATIVE_CASES = [
    ("project/http-client.env.json", "api-client-private-environment-file"),
    ("project/environment.json", "api-client-private-environment-file"),
    ("project/collection.json", "api-client-request-collection"),
    ("project/Insomnia.txt", "api-client-request-collection"),
]

SOURCES = [
    (
        "postman-authentication-value",
        "https://github.com/postmanlabs/postman-runtime/blob/develop/lib/authorizer/apikey.js",
    ),
    (
        "postman-authentication-value",
        "https://github.com/postmanlabs/postman-runtime/blob/develop/lib/authorizer/bearer.js",
    ),
    (
        "kafka-jaas-credential",
        "https://docs.oracle.com/en/java/javase/21/security/appendix-b-jaas-login-configuration-file.html",
    ),
    (
        "nuget-cleartext-credential",
        "https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials",
    ),
    (
        "npm-registry-encoded-credential",
        "https://docs.npmjs.com/cli/v11/configuring-npm/npmrc/#auth-related-configuration",
    ),
    ("kafka-jaas-credential", "https://kafka.apache.org/41/security/authentication-using-sasl/"),
    ("ldap-bind-credential", "https://arthurdejong.org/nss-pam-ldapd/nslcd.conf.5"),
    ("sssd-ldap-auth-token", "https://github.com/SSSD/sssd/blob/master/src/man/sssd-ldap.5.xml"),
    ("snmp-community-directive", "https://www.net-snmp.org/docs/man/snmpd.conf.html"),
    ("snmp-community-directive", "https://www.net-snmp.org/docs/man/snmp.conf.html"),
    ("redis-acl-credential", "https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/"),
    ("ipsec-shared-secret-entry", "https://github.com/strongswan/strongswan/blob/master/man/ipsec.secrets.5.in"),
    (
        "wireless-psk-configuration",
        "https://networkmanager.dev/docs/api/latest/settings-802-11-wireless-security.html",
    ),
    ("rsync-secrets-entry", "https://download.samba.org/pub/rsync/rsyncd.conf.5"),
    ("curl-config-credential", "https://curl.se/docs/manpage.html#-K"),
    ("curl-config-credential", "https://curl.se/docs/manpage.html#-u"),
    ("squid-parent-proxy-credential", "https://www.squid-cache.org/Doc/config/cache_peer/"),
    ("jupyter-legacy-password-hash", "https://jupyter-server.readthedocs.io/en/latest/operators/security.html"),
    (
        "azure-servicebus-shared-access-key",
        "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas",
    ),
    ("azure-servicebus-sas-token", "https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas"),
    ("google-oauth-refresh-token", "https://developers.google.com/identity/protocols/oauth2/web-server"),
    ("structured-sensitive-key-value", "https://docs.gitlab.com/api/project_level_variables/"),
    ("structured-sensitive-key-value", "https://schema.postman.com/json/collection/v2.1.0/docs/index.html"),
    ("http-sensitive-auth-header", "https://developer.hashicorp.com/vault/api-docs#authentication"),
    ("http-sensitive-auth-header", "https://docs.gitlab.com/api/rest/authentication/"),
    ("kubernetes-client-key-data", "https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/"),
    (
        "ansible-inventory-password",
        "https://docs.ansible.com/projects/ansible/latest/inventory_guide/connection_details.html",
    ),
    ("ansible-inventory-password", "https://docs.ansible.com/projects/ansible/latest/plugins/become.html"),
    ("aws-presigned-url", "https://docs.aws.amazon.com/AmazonS3/latest/developerguide/sigv4-query-string-auth.html"),
    ("postman-authentication-value", "https://schema.postman.com/json/collection/v2.1.0/docs/index.html"),
    ("anthropic-api-credential", "https://platform.claude.com/docs/en/cli-sdks-libraries/cli/authentication"),
    ("anthropic-api-credential", "https://platform.claude.com/docs/en/manage-claude/compliance-api-access"),
    ("api-client-private-environment-file", "https://www.jetbrains.com/help/idea/http-client-variables.html"),
    ("api-client-request-collection", "https://developer.konghq.com/inso-cli/reference/export/"),
    ("api-client-request-collection", "https://schema.postman.com/json/collection/v2.1.0/docs/index.html"),
    ("jupyter-legacy-password-hash", "https://github.com/jupyter/notebook/blob/6.5.x/notebook/auth/security.py"),
    (
        "bruno-api-key-auth-value",
        "https://github.com/usebruno/bruno/blob/main/packages/bruno-lang/v2/src/bruToJson.js",
    ),
    (
        "api-client-request-collection",
        "https://github.com/usebruno/bruno/blob/main/packages/bruno-lang/v2/src/bruToJson.js",
    ),
]
