"""Synthetic AD artifact filenames; metadata identity never validates secrets.

Export filenames for LAPS/BitLocker and named database copies are deliberate
heuristics, not a claim that Microsoft prescribes every accepted spelling.
Negative cases reject only the named rule; independent broad rules may report.
All additions are report-only and introduce no content reads or decryption.
"""

METADATA_CASES = (
    (
        "SYSVOL/example.test/Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Preferences/Groups/Groups.xml",
        "group-policy-preferences-file",
    ),
    (
        "\\\\dc\\SYSVOL\\example.test\\Policies\\{31B2F340-016D-11D2-945F-00C04FB984F9}\\User\\Preferences\\Drives\\Drives.xml.bak",
        "group-policy-preferences-file",
    ),
    ("backups/DomainSysvol/GPO/Machine/Preferences/Services/Services.xml.old", "group-policy-preferences-file"),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/User/Preferences/ScheduledTasks/ScheduledTasks.xml",
        "group-policy-preferences-file",
    ),
    ("Windows/System32/GroupPolicy/Machine/Preferences/DataSources/DataSources.xml", "group-policy-preferences-file"),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Preferences/Printers/Printers.xml",
        "group-policy-preferences-file",
    ),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Preferences/Registry/Registry.xml",
        "group-policy-preferences-file",
    ),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Scripts/Startup/Configure.ps1",
        "domain-policy-script-file",
    ),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/User/Scripts/Logon/MapDrives.cmd.old",
        "domain-policy-script-file",
    ),
    ("backups/DomainSysvol/GPO/Machine/Scripts/psscripts.ini", "domain-policy-script-file"),
    ("Windows/System32/GroupPolicy/User/Scripts/scripts.ini.bak", "domain-policy-script-file"),
    ("\\\\dc\\NETLOGON\\setup\\MapDrives.vbs", "domain-policy-script-file"),
    ("var/lib/samba/sysvol/example.test/scripts/users/connect.bat", "domain-policy-script-file"),
    ("NETLOGON/deployment/second/folder/job.wsf", "domain-policy-script-file"),
    ("Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Registry.pol", "group-policy-registry-file"),
    ("Windows/System32/GroupPolicy/User/Registry.pol.bak", "group-policy-registry-file"),
    ("backup/DomainSysvol/GPO/Machine/Registry.pol.old", "group-policy-registry-file"),
    ("Windows/System32/CertLog/Example Issuing CA.edb", "certificate-authority-database-file"),
    ("C:\\Windows\\System32\\CertLog\\Исходящий УЦ.edb.bak", "certificate-authority-database-file"),
    ("backup/Database/certbkxp.dat", "certificate-authority-database-file"),
    ("CA_Backup/Database/Example Issuing CA.edb.20260905", "certificate-authority-database-file"),
    ("ADCS-backups/Database/Issuer.edb.old", "certificate-authority-database-file"),
    ("ProgramData/Microsoft/Crypto/RSA/MachineKeys/a1b2c3d4_key-guid", "windows-cryptographic-key-store-file"),
    ("C:\\ProgramData\\Microsoft\\Crypto\\Keys\\cng-key-container", "windows-cryptographic-key-store-file"),
    (
        "Users/service/AppData/Roaming/Microsoft/Crypto/RSA/S-1-5-21-123-456-789-1001/private-container",
        "windows-cryptographic-key-store-file",
    ),
    ("ProgramData/Microsoft/Crypto/DSS/MachineKeys/key-container.bak", "windows-cryptographic-key-store-file"),
    ("ProgramData/Microsoft/Crypto/SystemKeys/cng-system-key", "windows-cryptographic-key-store-file"),
    ("backup/Microsoft.IdentityServer.ServiceHost.exe.config", "adfs-service-configuration-file"),
    ("Windows/ADFS/Microsoft.IdentityServer.ServiceHost.exe.config.bak", "adfs-service-configuration-file"),
    ("Windows/WID/Data/AdfsConfiguration.mdf", "adfs-configuration-database-file"),
    ("Windows/WID/Data/AdfsConfigurationV3_log.ldf", "adfs-configuration-database-file"),
    ("backup/AdfsConfigurationV4.bak", "adfs-configuration-database-file"),
    ("C:\\backup\\AdfsConfigurationV4.mdf.bak.old", "adfs-configuration-database-file"),
    ("Program Files/Microsoft Azure AD Sync/Data/ADSync.mdf", "entra-connect-database-file"),
    ("C:\\Program Files\\Microsoft Azure AD Sync\\Data\\ADSync_log.ldf.bak", "entra-connect-database-file"),
    ("backup/ADSync.bak.20260905", "entra-connect-database-file"),
    ("Program Files/Microsoft Azure AD Sync/Bin/miiserver.exe.config", "entra-connect-service-configuration"),
    (
        "C:\\Program Files\\Microsoft Azure AD Sync\\Bin\\miisclient.exe.config.old",
        "entra-connect-service-configuration",
    ),
    ("ProgramData/AADConnect/Applied-SynchronizationPolicy-20260905.json", "entra-connect-settings-export"),
    ("Exported-ServerConfiguration-20260905/MigratedPolicy.json", "entra-connect-settings-export"),
    ("backup/AADConnect/configuration.json.bak", "entra-connect-settings-export"),
    ("var/lib/samba/private/sam.ldb", "samba-directory-database-file"),
    ("sam.ldb.old", "samba-directory-database-file"),
    ("var/lib/samba/private/sam.ldb.d/DC=example,DC=test.ldb", "samba-directory-database-file"),
    ("C:\\backup\\sam.ldb.d\\CN=CONFIGURATION,DC=example,DC=test.ldb.bak", "samba-directory-database-file"),
    ("var/lib/samba/private/secrets.ldb", "samba-secret-database-file"),
    ("var/lib/samba/private/secrets.tdb.old", "samba-secret-database-file"),
    ("backups/secrets.ldb.bak.1", "samba-secret-database-file"),
    ("var/lib/samba/private/passdb.tdb", "samba-password-database-file"),
    ("etc/samba/smbpasswd", "samba-password-database-file"),
    ("smbpasswd.20260905", "samba-password-database-file"),
    ("backup/passdb.tdb.bak.old", "samba-password-database-file"),
    ("samba-backup-example.test-2026-09-05T12-30-00.tar.bz2", "samba-domain-backup-archive"),
    ("samba-backup-2026-09-05T12-30-00.123456.tar.bz2.old", "samba-domain-backup-archive"),
    ("C:\\backups\\samba-backup-EXAMPLE.TEST-2026-09-05T12-30-00.tar.bz2.bak", "samba-domain-backup-archive"),
    ("LAPS.csv", "laps-password-export-file"),
    ("Windows-LAPS-Passwords-20260905.xlsx", "laps-password-export-file"),
    ("exports/LAPS_credentials.json.bak", "laps-password-export-file"),
    ("ms-Mcs-AdmPwd.csv", "laps-password-export-file"),
    ("msLAPS-EncryptedPasswordHistory.clixml", "laps-password-export-file"),
    ("msLAPS-EncryptedDSRMPasswordHistory.clixml", "laps-password-export-file"),
    ("LAPS.ldf", "laps-password-export-file"),
    ("msLAPS-Password.ldif.bak", "laps-password-export-file"),
    ("msLAPS.Password.json", "laps-password-export-file"),
    ("LAPSpasswords.txt", "laps-password-export-file"),
    ("BitLocker Recovery Key {31B2F340-016D-11D2-945F-00C04FB984F9}.txt", "bitlocker-recovery-export-file"),
    ("BitLocker-Recovery-Passwords-20260905.csv.bak", "bitlocker-recovery-export-file"),
    ("Ключ восстановления BitLocker {31B2F340-016D-11D2-945F-00C04FB984F9}.TXT", "bitlocker-recovery-export-file"),
    ("BitLocker Keys.xlsx", "bitlocker-recovery-export-file"),
    ("BitLocker Recovery Passwords.pdf", "bitlocker-recovery-export-file"),
    ("{31B2F340-016D-11D2-945F-00C04FB984F9}.BEK", "bitlocker-external-key-file"),
    ("external/startup.bek.old", "bitlocker-external-key-file"),
    ("BitLocker Key Package {31B2F340-016D-11D2-945F-00C04FB984F9}.KPG", "bitlocker-key-package-file"),
    ("backup/recovery.kpg.bak", "bitlocker-key-package-file"),
    ("tickets/admin.kirbi", "kerberos-credential-cache"),
    ("tickets/service.kirbi.bak.old", "kerberos-credential-cache"),
    ("var/tmp/krb5cc_1000", "kerberos-credential-cache"),
    ("private/dns.keytab", "kerberos-credential-cache"),
    ("etc/krb5.keytab.20260905", "kerberos-credential-cache"),
    ("krb5cc_1001_example.test", "kerberos-credential-cache"),
    ("tickets/admin.ccache~", "kerberos-credential-cache"),
    ("IFM/Active Directory/ntds.dit", "windows-security-database-file"),
    ("IFM/registry/SYSTEM", "windows-security-database-file"),
    ("Program Files/Microsoft AD LDS/instance1/data/adamntds.dit.bak", "windows-security-database-file"),
    ("Windows/System32/config/RegBack/SAM.hiv.bak", "windows-security-database-file"),
    ("backup/SYSTEM.hive.bak.1", "windows-security-database-file"),
    ("backup/SECURITY.hiv.old", "windows-security-database-file"),
    ("backup/NTUSER.DAT.bak.old", "windows-security-database-file"),
    ("backup/SAM.sav.bak", "windows-security-database-file"),
    ("backup/SYSTEM.alt.old", "windows-security-database-file"),
    ("backup/NTUSER.DAT.log.bak", "windows-security-database-file"),
    ("backup/custom-directory.dit", "windows-security-database-file"),
    ("DeploymentShare$/Control/Bootstrap.ini", "domain-deployment-configuration"),
    ("Bootstrap.ini.bak", "domain-deployment-configuration"),
    ("Control/CustomSettings.ini.bak.old", "domain-deployment-configuration"),
    ("unattend.xml.20260905", "domain-deployment-configuration"),
    ("Autounattend.xml.save", "domain-deployment-configuration"),
    ("sysprep.inf.old", "domain-deployment-configuration"),
    ("systemstate.bkf", "backup-image-file"),
    ("ADLDS-instance1.bkf.bak", "backup-image-file"),
    ("disk-image.tibx.20260905", "backup-image-file"),
)

NEGATIVE_CASES = (
    ("project/Groups.xml", "group-policy-preferences-file"),
    ("project/Preferences/Groups/Groups.xml", "group-policy-preferences-file"),
    ("Policies/not-a-guid/Machine/Preferences/Groups/Groups.xml", "group-policy-preferences-file"),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Preferences/Groups/Services.xml",
        "group-policy-preferences-file",
    ),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Preferences/Groups/Groups.xml.example",
        "group-policy-preferences-file",
    ),
    (
        "NotPolicies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Preferences/Groups/Groups.xml",
        "group-policy-preferences-file",
    ),
    ("app/logon.ps1", "domain-policy-script-file"),
    ("SYSVOLexample.test/scripts/install.bat", "domain-policy-script-file"),
    ("MYNETLOGON/scripts/install.bat", "domain-policy-script-file"),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Scripts/Startup/readme.txt",
        "domain-policy-script-file",
    ),
    (
        "Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Scripts/Startup/install.ps1.example",
        "domain-policy-script-file",
    ),
    ("NETLOGON/guide.pdf", "domain-policy-script-file"),
    ("project/Registry.pol", "group-policy-registry-file"),
    ("Policies/{31B2F340-016D-11D2-945F-00C04FB984F9}/Machine/Registry.pol.example", "group-policy-registry-file"),
    ("GroupPolicyBackup/User/Registry.pol", "group-policy-registry-file"),
    ("exchange/Mailbox.edb", "certificate-authority-database-file"),
    ("project/Database/ordinary.edb", "certificate-authority-database-file"),
    ("Windows/System32/CertLog/Issuer.cer", "certificate-authority-database-file"),
    ("certbkxp.dat.example", "certificate-authority-database-file"),
    ("project/NotCertLog/Issuer.edb", "certificate-authority-database-file"),
    ("ProgramData/Microsoft/CryptoPublic/Keys/name", "windows-cryptographic-key-store-file"),
    ("project/Keys/private-container", "windows-cryptographic-key-store-file"),
    ("Microsoft/Crypto/RSA/PublicKeys/key", "windows-cryptographic-key-store-file"),
    ("Microsoft/Crypto/RSA/MachineKeys/subfolder/readme", "windows-cryptographic-key-store-file"),
    ("Microsoft/Crypto/RSA/MachineKeys", "windows-cryptographic-key-store-file"),
    ("Microsoft/Crypto/RSA/not-a-sid/key", "windows-cryptographic-key-store-file"),
    ("project/ServiceHost.exe.config", "adfs-service-configuration-file"),
    ("Microsoft.IdentityServer.ServiceHost.exe.config.example", "adfs-service-configuration-file"),
    ("NotMicrosoft.IdentityServer.ServiceHost.exe.config", "adfs-service-configuration-file"),
    ("app/configuration.mdf", "adfs-configuration-database-file"),
    ("AdfsConfigurationGuide.mdf", "adfs-configuration-database-file"),
    ("AdfsConfigurationV4.xml", "adfs-configuration-database-file"),
    ("AdfsConfigurationV4.mdf.example", "adfs-configuration-database-file"),
    ("ADSync.log", "entra-connect-database-file"),
    ("ADSyncReport.mdf", "entra-connect-database-file"),
    ("ADSync.mdf.example", "entra-connect-database-file"),
    ("app/miiserver.exe.config", "entra-connect-service-configuration"),
    ("Microsoft Identity Manager/Bin/miiserver.exe.config", "entra-connect-service-configuration"),
    ("Microsoft Azure AD SyncBackup/Bin/miiserver.exe.config", "entra-connect-service-configuration"),
    ("Microsoft Azure AD Sync/Bin/miiserver.exe.config.example", "entra-connect-service-configuration"),
    ("project/MigratedPolicy.json", "entra-connect-settings-export"),
    ("project/NotAADConnect/config.json", "entra-connect-settings-export"),
    ("Exported-ServerConfiguration-20260905/readme.json", "entra-connect-settings-export"),
    ("AADConnect/settings.json.example", "entra-connect-settings-export"),
    ("app/not-sam.ldb", "samba-directory-database-file"),
    ("app/database.ldb", "samba-directory-database-file"),
    ("sam.ldb.d/metadata.tdb", "samba-directory-database-file"),
    ("sam.ldb.example", "samba-directory-database-file"),
    ("sam.ldb.d/partition.ldb.example", "samba-directory-database-file"),
    ("app/secrets.db", "samba-secret-database-file"),
    ("app/secrets-notes.ldb", "samba-secret-database-file"),
    ("secrets.tdb.example", "samba-secret-database-file"),
    ("app/passdb.sqlite", "samba-password-database-file"),
    ("smbpasswd-guide.txt", "samba-password-database-file"),
    ("smbpasswd.example", "samba-password-database-file"),
    ("passdb.tdb.example", "samba-password-database-file"),
    ("other-backup-20260905.tar.bz2", "samba-domain-backup-archive"),
    ("samba-backup-readme.txt", "samba-domain-backup-archive"),
    ("samba-backup.tar.bz2", "samba-domain-backup-archive"),
    ("samba-backup-example.tar.bz2.example", "samba-domain-backup-archive"),
    ("elapsed-laps.csv", "laps-password-export-file"),
    ("LAPS-Audit.csv", "laps-password-export-file"),
    ("LAPS-installation-guide.txt", "laps-password-export-file"),
    ("LAPS-Passwords.csv.example", "laps-password-export-file"),
    ("BitLocker-policy.csv", "bitlocker-recovery-export-file"),
    ("BitLocker-installation-guide.txt", "bitlocker-recovery-export-file"),
    ("Recovery Key.txt", "bitlocker-recovery-export-file"),
    ("BitLocker Recovery Key {31B2F340-016D-11D2-945F-00C04FB984F9}.txt.example", "bitlocker-recovery-export-file"),
    ("key.bek.txt", "bitlocker-external-key-file"),
    ("key.bek.example", "bitlocker-external-key-file"),
    ("key.kpg.txt", "bitlocker-key-package-file"),
    ("key.kpg.example", "bitlocker-key-package-file"),
    ("tickets/ticket.kirbi.txt", "kerberos-credential-cache"),
    ("tickets/ticket.kirbi.example", "kerberos-credential-cache"),
    ("krb5cc_", "kerberos-credential-cache"),
    ("docs/krb5.conf", "kerberos-credential-cache"),
    ("directory.dit.example", "windows-security-database-file"),
    ("SAM.hive.example", "windows-security-database-file"),
    ("SYSTEM.alt.example", "windows-security-database-file"),
    ("SECURITY.alt.bak", "windows-security-database-file"),
    ("notes/SYSTEM-guide.txt", "windows-security-database-file"),
    ("Bootstrap.ini.example", "domain-deployment-configuration"),
    ("bootstrapping.ini", "domain-deployment-configuration"),
    ("NTBackup-guide.txt", "backup-image-file"),
    ("restore.bkf.example", "backup-image-file"),
)

SOURCES = (
    (
        "group-policy-preferences-file",
        "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gppref/d315342d-41c0-47e3-ab96-7039eb91f5b4",
    ),
    (
        "domain-policy-script-file",
        "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpscr/1e1641a3-a376-4aaa-96b9-4873a3052fd6",
    ),
    (
        "domain-policy-script-file",
        "https://github.com/samba-team/samba/blob/master/python/samba/provision/__init__.py",
    ),
    (
        "group-policy-registry-file",
        "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpreg/5c092c22-bf6b-4e7f-b180-b20743d368f5",
    ),
    (
        "certificate-authority-database-file",
        "https://learn.microsoft.com/en-us/windows/win32/seccertenroll/about-certificate-directory",
    ),
    (
        "certificate-authority-database-file",
        "https://learn.microsoft.com/en-us/troubleshoot/windows-server/certificates-and-public-key-infrastructure-pki/move-certification-authority-to-another-server",
    ),
    (
        "windows-cryptographic-key-store-file",
        "https://learn.microsoft.com/en-us/windows/win32/seccng/key-storage-and-retrieval",
    ),
    (
        "adfs-service-configuration-file",
        "https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/adfs-sql-latency",
    ),
    (
        "adfs-configuration-database-file",
        "https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server",
    ),
    (
        "adfs-configuration-database-file",
        "https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-the-ad-fs-configuration-database",
    ),
    (
        "entra-connect-database-file",
        "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-move-db",
    ),
    (
        "entra-connect-service-configuration",
        "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/tshoot-connect-connectivity",
    ),
    (
        "entra-connect-settings-export",
        "https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-import-export-config",
    ),
    (
        "samba-directory-database-file",
        "https://github.com/samba-team/samba/blob/master/python/samba/provision/__init__.py",
    ),
    (
        "samba-directory-database-file",
        "https://github.com/samba-team/samba/blob/master/python/samba/netcmd/domain/backup.py",
    ),
    ("samba-secret-database-file", "https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html"),
    ("samba-password-database-file", "https://www.samba.org/samba/docs/current/man-html/smbpasswd.5.html"),
    ("samba-password-database-file", "https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html"),
    (
        "samba-domain-backup-archive",
        "https://github.com/samba-team/samba/blob/master/python/samba/netcmd/domain/backup.py",
    ),
    (
        "laps-password-export-file",
        "https://learn.microsoft.com/en-us/powershell/module/laps/get-lapsadpassword?view=windowsserver2025-ps",
    ),
    (
        "bitlocker-recovery-export-file",
        "https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/recovery-overview",
    ),
    (
        "bitlocker-external-key-file",
        "https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/recovery-overview",
    ),
    (
        "bitlocker-key-package-file",
        "https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/recovery-overview",
    ),
    ("kerberos-credential-cache", "https://web.mit.edu/kerberos/krb5-latest/doc/basic/ccache_def.html"),
    ("kerberos-credential-cache", "https://web.mit.edu/kerberos/krb5-latest/doc/basic/keytab_def.html"),
    (
        "kerberos-credential-cache",
        "https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/kerberos/kuhl_m_kerberos.c",
    ),
    (
        "windows-security-database-file",
        "https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc732530(v=ws.11)",
    ),
    ("windows-security-database-file", "https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry-hives"),
    ("domain-deployment-configuration", "https://learn.microsoft.com/en-us/intune/configmgr/mdt/use-the-mdt"),
    (
        "backup-image-file",
        "https://learn.microsoft.com/en-us/previous-versions/windows/desktop/adam/backing-up-an-instance",
    ),
)
