"""Synthetic AD rule-pack 2.6 lexical evidence fixtures and primary format sources.

These candidates do not authenticate, unlock volumes, decrypt protected AD blobs,
or recover passwords. Structured AD inspectors own semantic decoding/validation.
"""

CONTENT_CASES = [
    ("users.ldf", 'description: password="NoteFixture!"', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"password=\'NoteFixture!\'"}', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"password=\\"NoteFixture!\\""}', "ad-directory-credential-note"),
    ("CustomSettings.ini", 'DomainAdminPassword=" $uperSecret! "', "windows-deployment-account-password"),
    (
        "tickets.hashes",
        "$krb5tgs$17$alice$EXAMPLE.TEST$*HTTP/app.example.test*$121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$23$12121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$HTTP/app.example.test:12121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "variables.json",
        '{"OSDLocalAdminPassword":"LocalAdminDeploymentFixture!"}',
        "windows-deployment-account-password",
    ),
    (
        "users.ldif",
        "dn: CN=alice,DC=example,DC=test\ndescription: Initial password=NoteFixturePass! for service access",
        "ad-directory-credential-note",
    ),
    ("users.ldf", "info: service account; пароль: NoteFixturePass!", "ad-directory-credential-note"),
    (
        "ad-users.json",
        '[{"sAMAccountName":"alice","description":"Initial password=NoteFixturePass!"}]',
        "ad-directory-credential-note",
    ),
    ("directory.txt", "Description : backup user; pwd=BackupFixture!", "ad-directory-credential-note"),
    ("ad-users.json", '{"comment":"password=QuotedFixture!; rotate later"}', "ad-directory-credential-note"),
    ("directory.ldf", "ms-Mcs-AdmPwd: LapsFixturePassword!\n", "ad-legacy-laps-password"),
    ("laps.txt", '"ms-Mcs-AdmPwd": "Short P!"', "ad-legacy-laps-password"),
    ("directory.ldif", "ms-Mcs-AdmPwd: A", "ad-legacy-laps-password"),
    (
        "laps.ldif",
        'msLAPS-Password: {"n":"Administrator","t":"1d94a4dbbf0b87d","p":"LapsModernFixture!"}',
        "ad-laps-password-json",
    ),
    (
        "laps.json",
        '{"msLAPS-Password":{"p":"Quote\\"Fixture!","n":"Administrator","t":"1d94a4dbbf0b87d"}}',
        "ad-laps-password-json",
    ),
    ("laps.json", '{"msLAPS-Password":{"p":"$uperSecret!","n":"Administrator"}}', "ad-laps-password-json"),
    (
        "laps.ldif",
        "msLAPS-EncryptedPassword:: AQAAANCMnd8BFdERjHoAwE/Cl+sAAAAAAAAAAAAAAAAAAAAA",
        "ad-laps-encrypted-password-attribute",
    ),
    (
        "laps.ldf",
        "msLAPS-EncryptedDSRMPasswordHistory:: AQAAANCMnd8BFdERjHoAwE/Cl+sAAAAAAAAAAAAAAAAAAAAA",
        "ad-laps-encrypted-password-attribute",
    ),
    (
        "serviceaccounts.ldif",
        "msDS-ManagedPassword:: AQAAACgAAAAQAAAAIAAAACIAAAAAAAAAAAAAAAAAAAAAAA==",
        "ad-gmsa-managed-password-attribute",
    ),
    (
        "change-password.ldf",
        "unicodePwd:: IgBVAG4AaQBjAG8AZABlAEYAaQB4AHQAdQByAGUAIQAiAA==",
        "ad-directory-unicode-password-attribute",
    ),
    (
        "recovery.ldif",
        "msFVE-RecoveryPassword: 000011-000022-000033-000044-000055-000066-000077-000088",
        "ad-bitlocker-recovery-password",
    ),
    (
        "BitLocker.txt",
        "BitLocker Recovery Key: 000011 000022 000033 000044 000055 000066 000077 000088",
        "ad-bitlocker-recovery-password",
    ),
    (
        "recovery.json",
        '"RecoveryPassword":"000011000022000033000044000055000066000077000088"',
        "ad-bitlocker-recovery-password",
    ),
    ("CustomSettings.ini", "DomainAdminPassword=DomainJoinFixture!\n", "windows-deployment-account-password"),
    ("tsenv.json", '{"OSDJoinPassword":"TaskSequenceFixture!"}', "windows-deployment-account-password"),
    (
        "DeploymentShare/Control/Bootstrap.ini",
        "UserPassword=DeploymentAccessFixture!",
        "mdt-deployment-access-password",
    ),
    ("CustomSettings.ini.old", "DBPwd=DeploymentDatabaseFixture!", "mdt-deployment-access-password"),
    ("CustomSettings.ini", "AdminPassword=LocalAdminFixture!", "mdt-deployment-access-password"),
    ("dcpromo.txt", "[DCInstall]\nSafeModeAdminPassword=DsrmFixturePassword!\n", "ad-dsrm-password-setting"),
    ("CustomSettings.ini", 'SafeModeAdminPassword="Space Dsrm!"', "ad-dsrm-password-setting"),
    (
        "dump.ntds",
        "EXAMPLE\\alice:1104:aad3b435b51404eeaad3b435b51404ee:11223344556677889900aabbccddeeff:::",
        "windows-account-ntlm-dump",
    ),
    (
        "dump.sam",
        "Administrator:500:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::",
        "windows-account-ntlm-dump",
    ),
    (
        "dump.secrets",
        "EXAMPLE\\HOST$:aad3b435b51404eeaad3b435b51404ee:11223344556677889900aabbccddeeff:::",
        "windows-account-ntlm-dump",
    ),
    (
        "dump.cached",
        "EXAMPLE/alice:$DCC2$10240#alice#11223344556677889900aabbccddeeff: (2026-01-01)",
        "windows-cached-domain-logon-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$23$alice@EXAMPLE.TEST:12121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-asrep-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$alice@EXAMPLE.TEST:12121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-asrep-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$17$alice$EXAMPLE.TEST$121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-asrep-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$18$EXAMPLE.TESTalice$abababababababababababababababababababababababababababababababababababababababab$121212121212121212121212",
        "kerberos-asrep-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$23$*alice$EXAMPLE.TEST$HTTP/app.example.test*$12121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$17$alice$EXAMPLE.TEST$121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$18$alice$EXAMPLE.TEST$121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "dump.ntds.kerberos",
        "EXAMPLE\\krbtgt:aes256-cts-hmac-sha1-96:abababababababababababababababababababababababababababababababab",
        "kerberos-long-term-key-dump",
    ),
    (
        "dump.kerberos",
        "EXAMPLE\\alice:aes128-cts-hmac-sha1-96:abababababababababababababababab",
        "kerberos-long-term-key-dump",
    ),
    ("dump.secrets", "EXAMPLE\\HOST$:rc4_hmac:abababababababababababababababab", "kerberos-long-term-key-dump"),
    (
        "credential.clixml",
        '<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj RefId="0"><Props><S N="UserName">alice</S><SS N="Password">46006900780074007500720065002100</SS></Props></Obj></Objs>',
        "powershell-clixml-secure-string",
    ),
    (
        "cred2.xml",
        '<SS N="Password">01000000d08c9ddf0115d1118c7a00c04fc297ebabababababababababababababababababababababababababababababababab</SS>',
        "powershell-clixml-secure-string",
    ),
    ("credentials.xml.old", '<SS N="Password">4100</SS>', "powershell-clixml-secure-string"),
    ("dump.secrets", "dpapi_machinekey:0xabababababababababababababababababababab", "windows-dpapi-system-key-dump"),
    ("dump.secrets", "dpapi_userkey:0xabababababababababababababababababababab", "windows-dpapi-system-key-dump"),
    ("dump.ntds.cleartext", "EXAMPLE\\alice:CLEARTEXT:CleartextFixture!", "windows-cleartext-account-dump"),
    ("dump.secrets", "EXAMPLE\\HOST$:CLEARTEXT:0x46006900780074007500720065002100", "windows-cleartext-account-dump"),
]

NEGATIVE_CASES = [
    ("users.ldf", 'description: password="   "', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"password=\\"   \\""}', "ad-directory-credential-note"),
    ("laps.json", '"ms-Mcs-AdmPwd": "                                 ${PASSWORD}"', "ad-legacy-laps-password"),
    ("users.ldf", 'description: password="                 redacted"', "ad-directory-credential-note"),
    (
        "CustomSettings.ini",
        "DomainAdminPassword='                                 ${PASSWORD}                                 '",
        "windows-deployment-account-password",
    ),
    ("laps.json", '"ms-Mcs-AdmPwd": "  ${PASSWORD}  "', "ad-legacy-laps-password"),
    ("laps.json", '"ms-Mcs-AdmPwd": false', "ad-legacy-laps-password"),
    ("laps.json", '{"msLAPS-Password":{"p":" redacted "}}', "ad-laps-password-json"),
    ("CustomSettings.ini", 'DomainAdminPassword=" ${JOIN_PASSWORD} "', "windows-deployment-account-password"),
    ("dcpromo.ps1", "$SafeModeAdminPassword = Read-Host -AsSecureString", "ad-dsrm-password-setting"),
    ("directory.ldf", "ms-Mcs-AdmPwd: A\u0000B", "ad-legacy-laps-password"),
    ("directory.ldf", 'ms-Mcs-AdmPwd: "A\u0000B"', "ad-legacy-laps-password"),
    ("users.ldf", 'description: password=" redacted "', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"password=\\" ${PASSWORD} \\""}', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"password=\'redacted\'"}', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"public","other":"password=\\"Unowned!\\""}', "ad-directory-credential-note"),
    ("ad-users.json", '{"description":"password=", "other":"UnownedFixture!"}', "ad-directory-credential-note"),
    ("variables.txt", "OSDLocalAdminPassword=$localAdminPassword", "windows-deployment-account-password"),
    (
        "tickets.hashes",
        "$krb5tgs$17$alice$EXAMPLE.TEST$*HTTP/app.example.test*$1212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    ("users.ldif", "description: Service account owner is alice", "ad-directory-credential-note"),
    ("users.ldif", "description: password=${PASSWORD}", "ad-directory-credential-note"),
    ("users.ldif", "description: password=REDACTED", "ad-directory-credential-note"),
    ("users.ldif", "description: password=contact helpdesk", "ad-directory-credential-note"),
    ("users.ldif", "description: ask the owner for the password", "ad-directory-credential-note"),
    ("users.ldif", "description: User account\npassword=OutsideNoteFixture!", "ad-directory-credential-note"),
    (
        "ad-users.json",
        '[{"description":"public note"},{"password":"UnownedFixture!"}]',
        "ad-directory-credential-note",
    ),
    (
        "ad-users.json",
        '{"description":"public note","unrelated":"password=UnownedFixture!"}',
        "ad-directory-credential-note",
    ),
    ("users.ldif", "description:: cGFzc3dvcmQ9VW5kZWNvZGVkUGFzc3dvcmQh", "ad-directory-credential-note"),
    ("unrelated.json", '{"description":"password=NonDirectoryFixture!"}', "ad-directory-credential-note"),
    ("laps.txt", "ms-Mcs-AdmPwdExpirationTime: 133800000000000000", "ad-legacy-laps-password"),
    ("directory.ldif", "ms-Mcs-AdmPwd:: U3ludGhldGljUGFzc3dvcmQ=", "ad-legacy-laps-password"),
    ("laps.json", '"ms-Mcs-AdmPwd": null', "ad-legacy-laps-password"),
    ("laps.ps1", "ms-Mcs-AdmPwd = $password", "ad-legacy-laps-password"),
    ("laps.txt", 'ms-Mcs-AdmPwd: "   "', "ad-legacy-laps-password"),
    (
        "laps.json",
        '{"msLAPS-Password":{"n":"Administrator"},"elsewhere":{"p":"UnownedFixture!"}}',
        "ad-laps-password-json",
    ),
    ("laps.json", '{"msLAPS-Password":{"p":""},"p":"UnownedFixture!"}', "ad-laps-password-json"),
    ("laps.json", '{"msLAPS-PasswordExpirationTime":{"p":"PublicMetadata"}}', "ad-laps-password-json"),
    ("laps.json", '{"msLAPS-Password":{"p":"${PASSWORD}"}}', "ad-laps-password-json"),
    ("laps.json", '{"msLAPS-Password":{"p":"   "}}', "ad-laps-password-json"),
    (
        "laps.ldif",
        "msLAPS-CurrentPasswordVersion:: AQAAANCMnd8BFdERjHoAwE/Cl+sAAAAAAAAAAAAAAAAAAAAA",
        "ad-laps-encrypted-password-attribute",
    ),
    ("laps.ldif", "msLAPS-EncryptedPassword:: ${ENCRYPTED}", "ad-laps-encrypted-password-attribute"),
    ("laps.ldif", "msLAPS-EncryptedPassword:: AQAAANCMnd8BFdERjHoAwE/Cl+s!", "ad-laps-encrypted-password-attribute"),
    (
        "serviceaccounts.ldif",
        "msDS-ManagedPasswordId:: AQAAACgAAAAQAAAAIAAAACIAAAAAAAAAAAAAAAAAAAAAAA==",
        "ad-gmsa-managed-password-attribute",
    ),
    ("serviceaccounts.ldif", "msDS-ManagedPasswordInterval: 30", "ad-gmsa-managed-password-attribute"),
    ("serviceaccounts.ldif", "msDS-ManagedPassword:: [REDACTED]", "ad-gmsa-managed-password-attribute"),
    ("schema.ldif", "replace: unicodePwd", "ad-directory-unicode-password-attribute"),
    ("schema.ldif", "unicodePwd: System.Byte[]", "ad-directory-unicode-password-attribute"),
    ("schema.ldif", "unicodePwd:: Invalid===", "ad-directory-unicode-password-attribute"),
    ("directory.ldif", "msFVE-RecoveryGuid: e11e6c53-9c79-4abd-b1d4-d2a699f5f998", "ad-bitlocker-recovery-password"),
    (
        "recovery.txt",
        "msFVE-RecoveryPassword: 000011-000022-000033-000044-000055-000066-000077",
        "ad-bitlocker-recovery-password",
    ),
    ("recovery.txt", "invoice: 000011000022000033000044000055000066000077000088", "ad-bitlocker-recovery-password"),
    (
        "recovery.txt",
        "msFVE-RecoveryPassword: 0000110000220000330000440000550000660000770000881",
        "ad-bitlocker-recovery-password",
    ),
    ("CustomSettings.ini", "DomainAdmin=alice\nJoinDomain=example.test", "windows-deployment-account-password"),
    ("variables.txt", "OSDJoinPassword=${JOIN_PASSWORD}", "windows-deployment-account-password"),
    ("variables.txt", "OSDJoinPassword=$JoinPassword", "windows-deployment-account-password"),
    ("variables.txt", "OSDJoinPassword=%OSDJoinPassword%", "windows-deployment-account-password"),
    ("variables.txt", "OSDJoinAccountPassword=UnknownUnofficialField!", "windows-deployment-account-password"),
    ("unrelated.ini", "UserPassword=UnrelatedCredential!", "mdt-deployment-access-password"),
    ("Bootstrap.ini", "UserPassword=%USER_PASSWORD%", "mdt-deployment-access-password"),
    ("Bootstrap.ini", "UserPassword=", "mdt-deployment-access-password"),
    ("install.ps1", "Install-ADDSForest -SafeModeAdministratorPassword $securePassword", "ad-dsrm-password-setting"),
    ("dcpromo.txt", "SafeModeAdminPassword=$password", "ad-dsrm-password-setting"),
    ("dcpromo.txt", "SafeModeAdminPassword=${DSRM_PASSWORD}", "ad-dsrm-password-setting"),
    (
        "dump.ntds",
        "EXAMPLE\\alice:RID:aad3b435b51404eeaad3b435b51404ee:11223344556677889900aabbccddeefff:::",
        "windows-account-ntlm-dump",
    ),
    (
        "dump.ntds",
        "EXAMPLE\\alice:1104:aad3b435b51404eeaad3b435b51404ee:11223344556677889900aabbccddeef:::",
        "windows-account-ntlm-dump",
    ),
    (
        "dump.ntds",
        "EXAMPLE\\alice:1104:aad3b435b51404eeaad3b435b51404ee:11223344556677889900aabbccddeefff:::suffix",
        "windows-account-ntlm-dump",
    ),
    ("dump.cached", "$DCC2$0#alice#11223344556677889900aabbccddeefff", "windows-cached-domain-logon-hash"),
    ("dump.cached", "$DCC2$10240##11223344556677889900aabbccddeefff", "windows-cached-domain-logon-hash"),
    ("dump.cached", "$DCC2$10240#alice#11223344556677889900aabbccddeefffg", "windows-cached-domain-logon-hash"),
    (
        "asrep.hash",
        "$krb5asrep$99$alice@EXAMPLE.TEST:12121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-asrep-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$23$alice@EXAMPLE.TEST:121212121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-asrep-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$23$alice@EXAMPLE.TEST:12121212121212121212121212121212$ababababababababababababababababababababababababababababababababababababababababa",
        "kerberos-asrep-hash",
    ),
    (
        "asrep.hash",
        "$krb5asrep$18$alice$EXAMPLE.TEST$121212121212121212121212$ababababababababababababababababababababababababababababababababababababababababz",
        "kerberos-asrep-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$23$*alice$EXAMPLE.TEST$HTTP/app.example.test*$121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$18$alice$EXAMPLE.TEST$121212121212121212121212$ababababababababababababababababababababababababababababababababababababababababa",
        "kerberos-tgs-hash",
    ),
    (
        "tickets.hashes",
        "$krb5tgs$3$alice$EXAMPLE.TEST$121212121212121212121212$abababababababababababababababababababababababababababababababababababababababab",
        "kerberos-tgs-hash",
    ),
    ("keys.txt", "aes256-cts-hmac-sha1-96", "kerberos-long-term-key-dump"),
    (
        "dump.kerberos",
        "EXAMPLE\\alice:aes128-cts-hmac-sha1-96:abababababababababababababababababababababababababababababababab",
        "kerberos-long-term-key-dump",
    ),
    ("credential.clixml", '<S N="Password">PublicString</S>', "powershell-clixml-secure-string"),
    ("foreign.xml", "<SS>12345678</SS>", "powershell-clixml-secure-string"),
    ("credential.clixml", '<SS N="Password">REDACTED</SS>', "powershell-clixml-secure-string"),
    ("credential.clixml", '<SS N="Password">010</SS>', "powershell-clixml-secure-string"),
    ("credential.clixml", '<SS N="Password"></SS>', "powershell-clixml-secure-string"),
    ("dump.secrets", "dpapi_machinekey:0xababababababababababababababababababab", "windows-dpapi-system-key-dump"),
    ("dump.secrets", "dpapi_machinekey:0xababababababababababababababababababababg", "windows-dpapi-system-key-dump"),
    ("dump.secrets", "MasterKey : e11e6c53-9c79-4abd-b1d4-d2a699f5f998", "windows-dpapi-system-key-dump"),
    ("dump.ntds.cleartext", "EXAMPLE\\alice:CLEARTEXT:", "windows-cleartext-account-dump"),
    ("dump.ntds.cleartext", "EXAMPLE\\alice:CLEARTEXT:[REDACTED]", "windows-cleartext-account-dump"),
    ("dump.secrets", "CLEARTEXT:CleartextFixture!", "windows-cleartext-account-dump"),
]

SOURCES = [
    ("kerberos-tgs-hash", "https://github.com/hashcat/hashcat/blob/master/src/modules/module_19600.c"),
    ("kerberos-tgs-hash", "https://github.com/hashcat/hashcat/blob/master/src/modules/module_13100.c"),
    ("ad-directory-credential-note", "https://learn.microsoft.com/en-us/windows/win32/adschema/a-description"),
    ("ad-directory-credential-note", "https://learn.microsoft.com/en-us/windows/win32/adschema/a-info"),
    ("ad-directory-credential-note", "https://learn.microsoft.com/en-us/windows/win32/adschema/a-comment"),
    (
        "ad-legacy-laps-password",
        "https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-technical-reference",
    ),
    (
        "ad-laps-password-json",
        "https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-technical-reference",
    ),
    (
        "ad-laps-encrypted-password-attribute",
        "https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-technical-reference",
    ),
    (
        "ad-gmsa-managed-password-attribute",
        "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/a9019740-3d73-46ef-a9ae-3ea8eb86ac2e",
    ),
    (
        "ad-directory-unicode-password-attribute",
        "https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2",
    ),
    (
        "ad-bitlocker-recovery-password",
        "https://learn.microsoft.com/en-us/windows/win32/secprov/protectkeywithnumericalpassword-win32-encryptablevolume",
    ),
    ("windows-deployment-account-password", "https://learn.microsoft.com/en-us/intune/configmgr/mdt/properties"),
    (
        "windows-deployment-account-password",
        "https://learn.microsoft.com/en-us/intune/configmgr/osd/understand/task-sequence-variables",
    ),
    ("mdt-deployment-access-password", "https://learn.microsoft.com/en-us/intune/configmgr/mdt/properties"),
    ("ad-dsrm-password-setting", "https://learn.microsoft.com/en-us/intune/configmgr/mdt/properties"),
    (
        "ad-dsrm-password-setting",
        "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/troubleshooting-domain-controller-deployment",
    ),
    ("windows-account-ntlm-dump", "https://github.com/fortra/impacket/blob/master/impacket/examples/secretsdump.py"),
    ("windows-cached-domain-logon-hash", "https://hashcat.net/wiki/doku.php?id=example_hashes"),
    (
        "windows-cached-domain-logon-hash",
        "https://github.com/fortra/impacket/blob/master/impacket/examples/secretsdump.py",
    ),
    ("kerberos-asrep-hash", "https://hashcat.net/wiki/doku.php?id=example_hashes"),
    ("kerberos-asrep-hash", "https://github.com/hashcat/hashcat/blob/master/src/modules/module_32100.c"),
    ("kerberos-asrep-hash", "https://github.com/hashcat/hashcat/blob/master/src/modules/module_32200.c"),
    ("kerberos-tgs-hash", "https://hashcat.net/wiki/doku.php?id=example_hashes"),
    ("kerberos-long-term-key-dump", "https://github.com/fortra/impacket/blob/master/impacket/examples/secretsdump.py"),
    (
        "powershell-clixml-secure-string",
        "https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/export-clixml",
    ),
    (
        "windows-dpapi-system-key-dump",
        "https://github.com/fortra/impacket/blob/master/impacket/examples/secretsdump.py",
    ),
    ("windows-dpapi-system-key-dump", "https://github.com/fortra/impacket/blob/master/impacket/dpapi.py"),
    (
        "windows-cleartext-account-dump",
        "https://github.com/fortra/impacket/blob/master/impacket/examples/secretsdump.py",
    ),
]
