"""Synthetic Russian-language examples; every credential here is a test fixture.

Only localizable user-defined labels are translated. LDAP/MS, JAAS classes,
protocol headers and provider token/hash alphabets keep their specified spelling.
"""

PASSWORD = "СложныйПарольЁжик!2027"
PHRASE = "Длинная парольная фраза; с пробелами!"
SHA512 = "$6$salt$" + "A" * 86
JAAS = "org.apache.kafka.common.security.plain.PlainLoginModule required "

CONTENT_CASES = (
    ("app.ini", f"БД_password='{PASSWORD}'", "assigned-secret"),
    ("app.json", f'{{"Сервис_api_key":"{PASSWORD}"}}', "assigned-secret"),
    ("app.yml", f'Ёжик_БД_client_secret: "{PHRASE}"', "assigned-secret"),
    ("app.txt", f"password='{PASSWORD}'", "credential-assignment-candidate"),
    ("app.ini", "secret=ЁЁЁЁЁЁ", "credential-assignment-candidate"),
    ("app.ini", "api_key=кириллицаБезЛатиницы", "credential-assignment-candidate"),
    ("app.json", f'{{"connection_string":{{"password":"{PHRASE}"}}}}', "generic-connection-string-password"),
    ("app.ini", f"connectionString=Server=lab;password='{PHRASE}';", "generic-connection-string-password"),
    ("app.ini", 'connectionString=Server=lab;password="Длинный""Пароль с пробелами!";', "generic-connection-string-password"),
    ("app.ini", "connectionString=Server=lab;password='Длинный''Пароль с пробелами!';", "generic-connection-string-password"),
    ("app.json", f'{{"СтрокаПодключения":{{"password":"{PASSWORD}"}}}}', "generic-connection-string-password"),
    ("app.yml", f'Строка_соединения: "server=lab;pwd={PASSWORD};"', "generic-connection-string-password"),
    ("app.xml", f"<Пароль>{PASSWORD}</Пароль>", "xml-password-element"),
    ("app.xml", f"<ПарольБД>{PASSWORD}</ПарольБД>", "xml-password-element"),
    ("app.xml", f"<настройки:password>{PASSWORD}</настройки:password>", "xml-password-element"),
    ("app.xml", f"<учёт:СекретКлиента><![CDATA[{PHRASE}<&>]]></учёт:СекретКлиента>", "xml-password-element"),
    ("app.xml", f'<Токен_доступа encoding="plain">{PASSWORD}</Токен_доступа>', "xml-password-element"),
    ("app.xml", f"<ПарольнаяФраза>{PHRASE}</ПарольнаяФраза>", "xml-password-element"),
    ("app.xml", f"<ПриватныйКлюч>{PASSWORD}</ПриватныйКлюч>", "xml-password-element"),
    ("app.xml", f"<КлючAPI>{PASSWORD}</КлючAPI>", "xml-password-element"),
    ("editors/Auto Save Session.sublime_session", f'{{"пароль":"{PASSWORD}"}}', "editor-session-text-secret"),
    ("editors/project.sublime-workspace", f"секрет клиента = '{PASSWORD}'", "editor-session-text-secret"),
    ("editors/state.vscdb", f"\x00токен_доступа={PASSWORD}\x00", "editor-session-binary-secret"),
    ("editors/state.vscdb", f'\x00"пароль":"{PASSWORD}"\x00', "editor-session-binary-secret"),
    ("vars.json", f'{{"key":"ПАРОЛЬ","value":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"name":"БД_password","value":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"имя":"Секрет клиента","значение":"{PHRASE}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ЗНАЧЕНИЕ":"{PASSWORD}","КЛЮЧ":"ПарольБД"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"наименование":"API-ключ","type":"secret","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"параметр":"Токен обновления","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"имя":"БД_Пароль","value":"{PASSWORD}","описание":"локальный тест"}}', "structured-sensitive-key-value"),
    ("vars.json", '{"ключ":"Пароль","значение":"Пароль\\\"сКавычкой!"}', "structured-sensitive-key-value"),
    ("etc/rsyncd.secrets", f"алиса:{PASSWORD}\n", "rsync-secrets-entry"),
    ("etc/rsyncd.secrets", f"@резервные-копии:{PHRASE}\r\n", "rsync-secrets-entry"),
    ("etc/rsyncd.secrets", f"ёлка.резерв:{PASSWORD}:сДвоеточием\n", "rsync-secrets-entry"),
    ("etc/shadow", f"алиса:{SHA512}:20000:0:99999:7:::\n", "unix-shadow-entry"),
    ("etc/shadow", f"ёлка-резерв:!{SHA512}:20000:0:99999:7:::\n", "unix-shadow-entry"),
    ("client.properties", JAAS + f'user_Алиса="{PASSWORD}";', "kafka-jaas-credential"),
    ("client.properties", JAAS + f'комментарий="тест" user_Ёлка="{PHRASE}";', "kafka-jaas-credential"),
    ("client.properties", JAAS + f'username="Алиса" password="{PASSWORD}";', "kafka-jaas-credential"),
)

NEGATIVE_CASES = (
    ("app.ini", f"БД_notpassword='{PASSWORD}'", "assigned-secret"),
    ("app.ini", 'БД_password="${DB_PASSWORD}"', "assigned-secret"),
    ("app.ini", 'БД_password="changeme"', "assigned-secret"),
    ("app.ini", "secret=яяжжё", "credential-assignment-candidate"),
    ("app.ini", "secret=пар\x00оль", "credential-assignment-candidate"),
    ("app.ini", "secret=пар\x7fоль", "credential-assignment-candidate"),
    ("app.ini", "secret=пар оль", "credential-assignment-candidate"),
    ("app.ini", f"логин={PASSWORD}", "credential-assignment-candidate"),
    ("app.ini", 'СтрокаПодключения: password="${DB_PASSWORD}"', "generic-connection-string-password"),
    ("app.ini", 'СтрокаПодключения: password="null"', "generic-connection-string-password"),
    ("app.ini", f'connectionString=Server=lab;password="{PHRASE}', "generic-connection-string-password"),
    ("app.ini", f'connectionString=Server=lab;login="{PASSWORD}"', "generic-connection-string-password"),
    ("app.xml", f"<Пароль>{PASSWORD}</Секрет>", "xml-password-element"),
    ("app.xml", f"<один:Пароль>{PASSWORD}</два:Пароль>", "xml-password-element"),
    ("app.xml", f"<Логин>{PASSWORD}</Логин>", "xml-password-element"),
    ("app.xml", f"<Ключ>{PASSWORD}</Ключ>", "xml-password-element"),
    ("app.xml", f"<ОткрытыйКлюч>{PASSWORD}</ОткрытыйКлюч>", "xml-password-element"),
    ("app.xml", f"<Сертификат>{PASSWORD}</Сертификат>", "xml-password-element"),
    ("app.xml", "<Пароль>${ПАРОЛЬ_БД}</Пароль>", "xml-password-element"),
    ("app.xml", "<Пароль><![CDATA[{{ секрет }}]]></Пароль>", "xml-password-element"),
    ("app.xml", f'<Пароль value="{PASSWORD}" />', "xml-password-element"),
    ("app.xml", f"<ПолитикаПароля>{PASSWORD}</ПолитикаПароля>", "xml-password-element"),
    ("editors/project.sublime-workspace", f"логин='{PASSWORD}'", "editor-session-text-secret"),
    ("editors/project.sublime-workspace", f"публичный_ключ='{PASSWORD}'", "editor-session-text-secret"),
    ("editors/state.vscdb", f"\x00сертификат={PASSWORD}\x00", "editor-session-binary-secret"),
    ("editors/state.vscdb", "\x00пароль=${ПАРОЛЬ_БД}\x00", "editor-session-binary-secret"),
    ("vars.json", f'[{{"ключ":"Пароль"}},{{"значение":"{PASSWORD}"}}]', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"Пароль","вложено":{{"значение":"{PASSWORD}"}}}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"Пароль","name":"Логин","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"Пароль","значение":"{PASSWORD}","value":"Другое"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"Логин","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"Ключ","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"Сертификат","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"ОткрытыйКлюч","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", f'{{"ключ":"СрокДействияПароля","значение":"{PASSWORD}"}}', "structured-sensitive-key-value"),
    ("vars.json", '{"ключ":"Пароль","значение":"${ПАРОЛЬ_БД}"}', "structured-sensitive-key-value"),
    ("vars.json", '{"ключ":"Пароль","значение":"   "}', "structured-sensitive-key-value"),
    ("vars.json", '{"ключ":"Пароль","значение":null}', "structured-sensitive-key-value"),
    ("notes.txt", f"алиса:{PASSWORD}\n", "rsync-secrets-entry"),
    ("etc/rsyncd.secrets", f"#алиса:{PASSWORD}\n", "rsync-secrets-entry"),
    ("etc/rsyncd.secrets", "алиса:\n", "rsync-secrets-entry"),
    ("etc/rsyncd.secrets", "алиса:${ПАРОЛЬ_БД}\n", "rsync-secrets-entry"),
    ("etc/shadow", "алиса:$6$salt$" + "Я" * 86 + ":20000:0:99999:7:::\n", "unix-shadow-entry"),
    ("etc/shadow", "алиса:$6$salt$" + "A" * 85 + ":20000:0:99999:7:::\n", "unix-shadow-entry"),
    ("etc/shadow", "алиса:x:20000:0:99999:7:::\n", "unix-shadow-entry"),
    ("client.properties", f'other.Module required user_Алиса="{PASSWORD}";', "kafka-jaas-credential"),
    ("client.properties", JAAS + f'username="Алиса"; unrelated user_Алиса="{PASSWORD}";', "kafka-jaas-credential"),
    ("client.properties", JAAS + f'user_Алиса="{PASSWORD}"', "kafka-jaas-credential"),
    ("client.properties", JAAS + 'user_Алиса="${ПАРОЛЬ}";', "kafka-jaas-credential"),
)

# Already-Unicode-capable detectors: these cases establish that no alphabet
# expansion or translation of a reserved option/header is necessary.
UNCHANGED_UNICODE_CASES = (
    ("app.ini", f'password="{PASSWORD}"', "assigned-secret"),
    ("app.xml", f"<GIUserPassword>{PASSWORD}</GIUserPassword>", "application-authentication-secret"),
    ("app.ini", f"Server=lab;Database=app;User ID=алиса;Password={PASSWORD};", "database-connection-string-password"),
    ("app.txt", f"postgresql://алиса:{PASSWORD}@db.example.test/app", "database-credential-uri"),
    ("app.txt", f"ftp://алиса:{PASSWORD}@ftp.example.test/", "ftp-uri-credential"),
    (".git-credentials", f"https://алиса:{PASSWORD}@git.example.test/repo", "git-credential-url"),
    (".netrc", f"machine lab.example.test login алиса password {PASSWORD}", "netrc-password"),
    ("app.xml", f"<password>{PHRASE}</password>", "xml-password-element"),
    ("etc/redis.conf", f'requirepass "{PHRASE}"', "redis-authentication-directive"),
    (".pgpass", f"localhost:5432:app:алиса:{PASSWORD}\n", "postgresql-password-entry"),
    ("NuGet.Config", f'<configuration><packageSourceCredentials><lab><add key="ClearTextPassword" value="{PASSWORD}" /></lab></packageSourceCredentials></configuration>', "nuget-cleartext-credential"),
    ("etc/ldap.conf", f"bindpw {PASSWORD}", "ldap-bind-credential"),
    ("etc/sssd/sssd.conf", f"ldap_default_authtok = {PASSWORD}", "sssd-ldap-auth-token"),
    ("etc/snmpd.conf", f"rocommunity {PASSWORD} localhost", "snmp-community-directive"),
    ("etc/users.acl", f"user алиса on >{PASSWORD} ~* +@all", "redis-acl-credential"),
    ("etc/ipsec.secrets", f'@local @remote : PSK "{PHRASE}"', "ipsec-shared-secret-entry"),
    (".curlrc", f'user = "алиса:{PASSWORD}"', "curl-config-credential"),
    ("inventory.ini", f"host ansible_password='{PASSWORD}'", "ansible-inventory-password"),
)

SOURCES = (
    ("xml-password-element", "https://www.w3.org/TR/xml/#NT-NameStartChar"),
    ("generic-connection-string-password", "https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings"),
    ("rsync-secrets-entry", "https://download.samba.org/pub/rsync/rsyncd.conf.5"),
    ("rsync-secrets-entry", "https://raw.githubusercontent.com/rsyncproject/rsync/master/authenticate.c"),
    ("unix-shadow-entry", "https://raw.githubusercontent.com/shadow-maint/shadow/master/lib/chkname.c"),
    ("kafka-jaas-credential", "https://raw.githubusercontent.com/apache/kafka/trunk/clients/src/main/java/org/apache/kafka/common/security/JaasConfig.java"),
    ("kafka-jaas-credential", "https://raw.githubusercontent.com/openjdk/jdk/master/src/java.base/share/classes/java/io/StreamTokenizer.java"),
    ("erlang-cookie-value", "https://raw.githubusercontent.com/erlang/otp/master/lib/kernel/src/auth.erl"),
    ("kubernetes-secret-manifest", "https://kubernetes.io/docs/concepts/configuration/secret/"),
)
